const allEmojis = [
  // Smileys & Emotion
  { char: "😀", keywords: ["grinning", "face", "smile", "happy"] },
  { char: "😃", keywords: ["smiley", "happy", "joy", "smile"] },
  { char: "😄", keywords: ["smile", "happy", "joy", "laugh"] },
  { char: "😁", keywords: ["grin", "happy", "smile", "joy"] },
  { char: "😆", keywords: ["laughing", "happy", "joy", "lol"] },
  { char: "😅", keywords: ["sweat", "smile", "relief", "nervous"] },
  { char: "🤣", keywords: ["rofl", "laughing", "lol", "happy"] },
  { char: "😂", keywords: ["joy", "tears", "laughing", "lol"] },
  { char: "🙂", keywords: ["smile", "happy", "simple"] },
  { char: "🙃", keywords: ["upside", "down", "silly"] },
  { char: "😉", keywords: ["wink", "flirt", "playful"] },
  { char: "😊", keywords: ["blush", "smile", "happy", "shy"] },
  { char: "😇", keywords: ["innocent", "angel", "halo"] },
  { char: "🥰", keywords: ["love", "hearts", "adore", "crush"] },
  { char: "😍", keywords: ["heart", "eyes", "love", "crush"] },
  { char: "🤩", keywords: ["star", "eyes", "excited", "wow"] },
  { char: "😘", keywords: ["kiss", "love", "heart", "flirt"] },
  { char: "😗", keywords: ["kiss", "love", "affection"] },
  { char: "😚", keywords: ["kiss", "closed", "eyes", "love"] },
  { char: "😙", keywords: ["kiss", "smile", "love"] },
  { char: "🥲", keywords: ["tear", "smile", "touched", "grateful"] },
  { char: "😋", keywords: ["yum", "tasty", "delicious", "tongue"] },
  { char: "😛", keywords: ["tongue", "playful", "silly"] },
  { char: "😜", keywords: ["wink", "tongue", "playful", "crazy"] },
  { char: "🤪", keywords: ["zany", "crazy", "silly", "wild"] },
  { char: "😝", keywords: ["tongue", "squint", "playful"] },
  { char: "🤑", keywords: ["money", "rich", "dollar", "greedy"] },
  { char: "🤗", keywords: ["hug", "friendly", "warm"] },
  { char: "🤭", keywords: ["oops", "giggle", "secret", "shy"] },
  { char: "🤫", keywords: ["shh", "quiet", "secret", "silence"] },
  { char: "🤔", keywords: ["thinking", "hmm", "consider", "wonder"] },
  { char: "🤐", keywords: ["zipper", "mouth", "secret", "quiet"] },
  { char: "🤨", keywords: ["raised", "eyebrow", "skeptical", "suspicious"] },
  { char: "😐", keywords: ["neutral", "meh", "blank"] },
  { char: "😑", keywords: ["expressionless", "blank", "deadpan"] },
  { char: "😶", keywords: ["no", "mouth", "silent", "speechless"] },
  { char: "😏", keywords: ["smirk", "sly", "smug"] },
  { char: "😒", keywords: ["unamused", "annoyed", "bored"] },
  { char: "🙄", keywords: ["eye", "roll", "annoyed", "whatever"] },
  { char: "😬", keywords: ["grimace", "awkward", "oops"] },
  { char: "🤥", keywords: ["lying", "pinocchio", "lie", "nose"] },
  { char: "😌", keywords: ["relieved", "calm", "peaceful"] },
  { char: "😔", keywords: ["pensive", "sad", "thoughtful"] },
  { char: "😪", keywords: ["sleepy", "tired", "yawn"] },
  { char: "🤤", keywords: ["drool", "hungry", "sleepy"] },
  { char: "😴", keywords: ["sleeping", "zzz", "tired"] },
  { char: "😷", keywords: ["mask", "sick", "medical", "covid"] },
  { char: "🤒", keywords: ["sick", "thermometer", "fever", "ill"] },
  { char: "🤕", keywords: ["injured", "bandage", "hurt"] },
  { char: "🤢", keywords: ["nausea", "sick", "disgusted"] },
  { char: "🤮", keywords: ["vomit", "sick", "puke"] },
  { char: "🤧", keywords: ["sneeze", "sick", "achoo"] },
  { char: "🥵", keywords: ["hot", "heat", "sweating"] },
  { char: "🥶", keywords: ["cold", "freezing", "ice"] },
  { char: "😎", keywords: ["cool", "sunglasses", "awesome"] },
  { char: "🤓", keywords: ["nerd", "geek", "glasses", "smart"] },
  { char: "🧐", keywords: ["monocle", "fancy", "curious"] },
  { char: "😕", keywords: ["confused", "uncertain", "puzzled"] },
  { char: "😟", keywords: ["worried", "concerned", "anxious"] },
  { char: "🙁", keywords: ["frown", "sad", "unhappy"] },
  { char: "☹️", keywords: ["frown", "sad", "unhappy"] },
  { char: "😮", keywords: ["wow", "surprised", "shocked"] },
  { char: "😯", keywords: ["hushed", "surprised", "quiet"] },
  { char: "😲", keywords: ["astonished", "shocked", "wow"] },
  { char: "😳", keywords: ["flushed", "embarrassed", "shy"] },
  { char: "🥺", keywords: ["pleading", "puppy", "eyes", "cute"] },
  { char: "😦", keywords: ["frown", "open", "mouth", "shocked"] },
  { char: "😧", keywords: ["anguished", "shocked", "worried"] },
  { char: "😨", keywords: ["fearful", "scared", "afraid"] },
  { char: "😰", keywords: ["anxious", "sweat", "nervous"] },
  { char: "😥", keywords: ["sad", "relieved", "disappointed"] },
  { char: "😢", keywords: ["cry", "sad", "tear"] },
  { char: "😭", keywords: ["sob", "cry", "bawling", "sad"] },
  { char: "😱", keywords: ["scream", "fear", "shocked", "omg"] },
  { char: "😖", keywords: ["confounded", "frustrated", "upset"] },
  { char: "😣", keywords: ["persevere", "struggle", "hard"] },
  { char: "😞", keywords: ["disappointed", "sad", "let down"] },
  { char: "😓", keywords: ["downcast", "sweat", "sad"] },
  { char: "😩", keywords: ["weary", "tired", "exhausted"] },
  { char: "😫", keywords: ["tired", "exhausted", "done"] },
  { char: "🥱", keywords: ["yawn", "tired", "bored"] },
  { char: "😤", keywords: ["triumph", "proud", "steam"] },
  { char: "😡", keywords: ["angry", "mad", "rage"] },
  { char: "😠", keywords: ["angry", "mad", "furious"] },
  { char: "🤬", keywords: ["cursing", "swearing", "angry", "symbols"] },
  { char: "👿", keywords: ["devil", "evil", "angry", "horns"] },
  { char: "😈", keywords: ["devil", "evil", "mischievous", "smiling"] },
  { char: "💀", keywords: ["skull", "death", "dead", "lol"] },
  { char: "☠️", keywords: ["skull", "crossbones", "death", "poison"] },
  { char: "💩", keywords: ["poop", "crap", "poo"] },
  { char: "🤡", keywords: ["clown", "funny", "circus"] },
  { char: "👹", keywords: ["ogre", "monster", "japanese"] },
  { char: "👺", keywords: ["goblin", "japanese", "monster"] },
  { char: "👻", keywords: ["ghost", "spooky", "boo"] },
  { char: "👽", keywords: ["alien", "ufo", "space"] },
  { char: "👾", keywords: ["space", "invader", "alien", "game"] },
  { char: "🤖", keywords: ["robot", "ai", "bot"] },

  // Gestures & Body Parts
  { char: "👋", keywords: ["wave", "hello", "hi", "bye"] },
  { char: "🤚", keywords: ["raised", "back", "hand", "stop"] },
  { char: "🖐️", keywords: ["hand", "five", "fingers", "stop"] },
  { char: "✋", keywords: ["raised", "hand", "stop", "high five"] },
  { char: "🖖", keywords: ["vulcan", "spock", "star trek"] },
  { char: "👌", keywords: ["ok", "okay", "perfect", "good"] },
  { char: "🤌", keywords: ["pinched", "fingers", "italian", "gesture"] },
  { char: "🤏", keywords: ["pinching", "small", "tiny"] },
  { char: "✌️", keywords: ["peace", "victory", "two"] },
  { char: "🤞", keywords: ["crossed", "fingers", "luck", "hope"] },
  { char: "🤟", keywords: ["love", "you", "rock", "sign"] },
  { char: "🤘", keywords: ["rock", "metal", "horns"] },
  { char: "🤙", keywords: ["call", "me", "shaka", "hang loose"] },
  { char: "👈", keywords: ["left", "point", "finger"] },
  { char: "👉", keywords: ["right", "point", "finger"] },
  { char: "👆", keywords: ["up", "point", "finger"] },
  { char: "🖕", keywords: ["middle", "finger", "rude"] },
  { char: "👇", keywords: ["down", "point", "finger"] },
  { char: "☝️", keywords: ["up", "point", "one", "finger"] },
  { char: "👍", keywords: ["thumbs", "up", "yes", "good", "like"] },
  { char: "👎", keywords: ["thumbs", "down", "no", "bad", "dislike"] },
  { char: "✊", keywords: ["fist", "punch", "power"] },
  { char: "👊", keywords: ["fist", "bump", "punch"] },
  { char: "🤛", keywords: ["left", "fist", "bump"] },
  { char: "🤜", keywords: ["right", "fist", "bump"] },
  { char: "👏", keywords: ["clap", "applause", "congrats", "bravo"] },
  { char: "🙌", keywords: ["raised", "hands", "celebration", "yay"] },
  { char: "👐", keywords: ["open", "hands", "hug"] },
  { char: "🤲", keywords: ["palms", "together", "prayer", "hold"] },
  { char: "🤝", keywords: ["handshake", "deal", "agreement"] },
  { char: "🙏", keywords: ["pray", "thanks", "please", "namaste"] },
  { char: "✍️", keywords: ["writing", "hand", "pencil", "write"] },
  { char: "💅", keywords: ["nail", "polish", "manicure", "sass"] },
  { char: "🤳", keywords: ["selfie", "camera", "phone"] },
  { char: "💪", keywords: ["muscle", "strong", "biceps", "flex"] },
  { char: "🦾", keywords: ["mechanical", "arm", "prosthetic"] },
  { char: "🦿", keywords: ["mechanical", "leg", "prosthetic"] },
  { char: "🦵", keywords: ["leg", "limb", "kick"] },
  { char: "🦶", keywords: ["foot", "kick", "stomp"] },
  { char: "👂", keywords: ["ear", "listen", "hear"] },
  { char: "🦻", keywords: ["ear", "hearing", "aid"] },
  { char: "👃", keywords: ["nose", "smell", "sniff"] },
  { char: "🧠", keywords: ["brain", "smart", "think"] },
  { char: "🦷", keywords: ["tooth", "dental", "dentist"] },
  { char: "🦴", keywords: ["bone", "skeleton"] },
  { char: "👀", keywords: ["eyes", "look", "watch", "see"] },
  { char: "👁️", keywords: ["eye", "look", "see"] },
  { char: "👅", keywords: ["tongue", "taste", "lick"] },
  { char: "👄", keywords: ["mouth", "lips", "kiss"] },

  // Hearts & Love
  { char: "❤️", keywords: ["heart", "love", "red"] },
  { char: "🧡", keywords: ["orange", "heart", "love"] },
  { char: "💛", keywords: ["yellow", "heart", "love"] },
  { char: "💚", keywords: ["green", "heart", "love"] },
  { char: "💙", keywords: ["blue", "heart", "love"] },
  { char: "💜", keywords: ["purple", "heart", "love"] },
  { char: "🖤", keywords: ["black", "heart", "love", "dark"] },
  { char: "🤍", keywords: ["white", "heart", "love", "pure"] },
  { char: "🤎", keywords: ["brown", "heart", "love"] },
  { char: "💔", keywords: ["broken", "heart", "sad", "breakup"] },
  { char: "❣️", keywords: ["heart", "exclamation", "love"] },
  { char: "💕", keywords: ["two", "hearts", "love"] },
  { char: "💞", keywords: ["revolving", "hearts", "love"] },
  { char: "💓", keywords: ["beating", "heart", "love"] },
  { char: "💗", keywords: ["growing", "heart", "love"] },
  { char: "💖", keywords: ["sparkling", "heart", "love"] },
  { char: "💘", keywords: ["arrow", "heart", "cupid", "love"] },
  { char: "💝", keywords: ["gift", "heart", "love", "present"] },
  { char: "💟", keywords: ["heart", "decoration", "love"] },
  { char: "💌", keywords: ["love", "letter", "heart", "mail"] },
  { char: "💋", keywords: ["kiss", "lipstick", "lips"] },
  { char: "💍", keywords: ["ring", "diamond", "engagement", "wedding"] },
  { char: "💎", keywords: ["gem", "diamond", "jewel", "precious"] },

  // Animals & Nature
  { char: "🐶", keywords: ["dog", "puppy", "pet"] },
  { char: "🐱", keywords: ["cat", "kitten", "pet"] },
  { char: "🐭", keywords: ["mouse", "rat", "rodent"] },
  { char: "🐹", keywords: ["hamster", "pet", "rodent"] },
  { char: "🐰", keywords: ["rabbit", "bunny", "easter"] },
  { char: "🦊", keywords: ["fox", "animal"] },
  { char: "🐻", keywords: ["bear", "animal"] },
  { char: "🐼", keywords: ["panda", "bear", "animal"] },
  { char: "🐨", keywords: ["koala", "bear", "australia"] },
  { char: "🐯", keywords: ["tiger", "animal", "cat"] },
  { char: "🦁", keywords: ["lion", "animal", "cat", "king"] },
  { char: "🐮", keywords: ["cow", "animal", "farm"] },
  { char: "🐷", keywords: ["pig", "animal", "farm"] },
  { char: "🐸", keywords: ["frog", "animal", "amphibian"] },
  { char: "🐵", keywords: ["monkey", "animal", "ape"] },
  { char: "🙈", keywords: ["see", "no", "evil", "monkey"] },
  { char: "🙉", keywords: ["hear", "no", "evil", "monkey"] },
  { char: "🙊", keywords: ["speak", "no", "evil", "monkey"] },
  { char: "🐒", keywords: ["monkey", "animal"] },
  { char: "🐔", keywords: ["chicken", "bird", "farm"] },
  { char: "🐧", keywords: ["penguin", "bird", "animal"] },
  { char: "🐦", keywords: ["bird", "animal"] },
  { char: "🐤", keywords: ["baby", "chick", "bird"] },
  { char: "🐣", keywords: ["hatching", "chick", "bird"] },
  { char: "🐥", keywords: ["front", "chick", "bird"] },
  { char: "🦆", keywords: ["duck", "bird", "animal"] },
  { char: "🦅", keywords: ["eagle", "bird", "america"] },
  { char: "🦉", keywords: ["owl", "bird", "wise"] },
  { char: "🦇", keywords: ["bat", "animal", "vampire"] },
  { char: "🐺", keywords: ["wolf", "animal"] },
  { char: "🐗", keywords: ["boar", "pig", "animal"] },
  { char: "🐴", keywords: ["horse", "animal"] },
  { char: "🦄", keywords: ["unicorn", "magical", "horse"] },
  { char: "🐝", keywords: ["bee", "insect", "honey"] },
  { char: "🐛", keywords: ["bug", "insect", "caterpillar"] },
  { char: "🦋", keywords: ["butterfly", "insect", "beautiful"] },
  { char: "🐌", keywords: ["snail", "slow", "shell"] },
  { char: "🐞", keywords: ["ladybug", "insect", "bug"] },
  { char: "🍀", keywords: ["four", "leaf", "clover", "luck"] },
  { char: "🎍", keywords: ["bamboo", "plant", "japanese"] },
  { char: "🎋", keywords: ["tanabata", "tree", "japanese"] },
  { char: "🍃", keywords: ["leaves", "wind", "nature"] },
  { char: "🍂", keywords: ["fallen", "leaves", "autumn", "fall"] },
  { char: "🍁", keywords: ["maple", "leaf", "canada", "fall"] },
  { char: "🍄", keywords: ["mushroom", "fungus", "nature"] },
  { char: "🌾", keywords: ["rice", "plant", "grain"] },
  { char: "💐", keywords: ["bouquet", "flowers", "gift"] },
  { char: "🌷", keywords: ["tulip", "flower", "spring"] },
  { char: "🌹", keywords: ["rose", "flower", "love", "red"] },
  { char: "🥀", keywords: ["wilted", "flower", "sad", "dead"] },
  { char: "🌺", keywords: ["hibiscus", "flower", "tropical"] },
  { char: "🌸", keywords: ["cherry", "blossom", "flower", "spring"] },
  { char: "🌼", keywords: ["blossom", "flower", "daisy"] },
  { char: "🌻", keywords: ["sunflower", "flower", "yellow"] },
  { char: "🌞", keywords: ["sun", "face", "sunny", "happy"] },
  { char: "🌝", keywords: ["full", "moon", "face", "night"] },
  { char: "🌛", keywords: ["first", "quarter", "moon", "face"] },
  { char: "🌜", keywords: ["last", "quarter", "moon", "face"] },
  { char: "🌚", keywords: ["new", "moon", "face", "dark"] },
  { char: "🌕", keywords: ["full", "moon", "night"] },
  { char: "🌖", keywords: ["waning", "gibbous", "moon"] },
  { char: "🌗", keywords: ["last", "quarter", "moon"] },
  { char: "🌘", keywords: ["waning", "crescent", "moon"] },
  { char: "🌑", keywords: ["new", "moon", "dark"] },
  { char: "🌒", keywords: ["waxing", "crescent", "moon"] },
  { char: "🌓", keywords: ["first", "quarter", "moon"] },
  { char: "🌔", keywords: ["waxing", "gibbous", "moon"] },
  { char: "🌙", keywords: ["crescent", "moon", "night"] },
  { char: "🌎", keywords: ["earth", "americas", "world", "planet"] },
  { char: "🌍", keywords: ["earth", "europe", "africa", "world"] },
  { char: "🌏", keywords: ["earth", "asia", "australia", "world"] },
  { char: "🪐", keywords: ["saturn", "planet", "rings", "space"] },
  { char: "💫", keywords: ["dizzy", "stars", "sparkle"] },
  { char: "⭐", keywords: ["star", "favorite", "gold"] },
  { char: "🌟", keywords: ["glowing", "star", "sparkle", "shiny"] },
  { char: "✨", keywords: ["sparkles", "shiny", "magic", "clean"] },
  { char: "⚡", keywords: ["lightning", "zap", "electric", "fast"] },
  { char: "☄️", keywords: ["comet", "space", "meteor"] },
  { char: "💥", keywords: ["collision", "boom", "explosion", "bang"] },
  { char: "🔥", keywords: ["fire", "hot", "lit", "flame"] },
  { char: "🌪️", keywords: ["tornado", "cyclone", "wind"] },
  { char: "🌈", keywords: ["rainbow", "colors", "pride", "weather"] },
  { char: "☀️", keywords: ["sun", "sunny", "weather", "bright"] },
  { char: "🌤️", keywords: ["sun", "behind", "cloud", "weather"] },
  { char: "⛅", keywords: ["sun", "behind", "cloud", "weather"] },
  { char: "🌥️", keywords: ["sun", "behind", "large", "cloud"] },
  { char: "☁️", keywords: ["cloud", "weather", "cloudy"] },
  { char: "🌦️", keywords: ["sun", "behind", "rain", "cloud"] },
  { char: "🌧️", keywords: ["rain", "cloud", "weather", "rainy"] },
  { char: "⛈️", keywords: ["thunder", "cloud", "rain", "storm"] },
  { char: "🌩️", keywords: ["cloud", "lightning", "thunder"] },
  { char: "🌨️", keywords: ["cloud", "snow", "cold", "weather"] },
  { char: "❄️", keywords: ["snowflake", "cold", "winter", "ice"] },
  { char: "☃️", keywords: ["snowman", "winter", "cold", "christmas"] },
  { char: "⛄", keywords: ["snowman", "without", "snow", "winter"] },
  { char: "🌬️", keywords: ["wind", "face", "blowing", "air"] },
  { char: "💨", keywords: ["dashing", "away", "wind", "fast"] },
  { char: "💧", keywords: ["droplet", "water", "sweat"] },
  { char: "💦", keywords: ["sweat", "droplets", "water", "splash"] },
  { char: "☔", keywords: ["umbrella", "rain", "weather"] },
  { char: "☂️", keywords: ["umbrella", "rain"] },
  { char: "🌊", keywords: ["water", "wave", "ocean", "sea"] },
  { char: "🌫️", keywords: ["fog", "cloud", "weather"] },

  // Food & Drink
  { char: "🍇", keywords: ["grapes", "fruit", "food"] },
  { char: "🍈", keywords: ["melon", "fruit", "food"] },
  { char: "🍉", keywords: ["watermelon", "fruit", "summer", "food"] },
  { char: "🍊", keywords: ["tangerine", "orange", "fruit", "food"] },
  { char: "🍋", keywords: ["lemon", "fruit", "sour", "food"] },
  { char: "🍌", keywords: ["banana", "fruit", "food"] },
  { char: "🍍", keywords: ["pineapple", "fruit", "tropical", "food"] },
  { char: "🥭", keywords: ["mango", "fruit", "tropical", "food"] },
  { char: "🍎", keywords: ["red", "apple", "fruit", "food"] },
  { char: "🍏", keywords: ["green", "apple", "fruit", "food"] },
  { char: "🍐", keywords: ["pear", "fruit", "food"] },
  { char: "🍑", keywords: ["peach", "fruit", "food", "butt"] },
  { char: "🍒", keywords: ["cherries", "fruit", "food", "red"] },
  { char: "🍓", keywords: ["strawberry", "fruit", "food", "berry"] },
  { char: "🫐", keywords: ["blueberries", "fruit", "food", "berry"] },
  { char: "🥝", keywords: ["kiwi", "fruit", "food", "green"] },
  { char: "🍅", keywords: ["tomato", "vegetable", "food", "red"] },
  { char: "🫒", keywords: ["olive", "food", "mediterranean"] },
  { char: "🥥", keywords: ["coconut", "fruit", "tropical", "food"] },
  { char: "🥑", keywords: ["avocado", "fruit", "food", "green"] },
  { char: "🍆", keywords: ["eggplant", "vegetable", "food", "purple"] },
  { char: "🥔", keywords: ["potato", "vegetable", "food"] },
  { char: "🥕", keywords: ["carrot", "vegetable", "food", "orange"] },
  { char: "🌽", keywords: ["corn", "vegetable", "food", "maize"] },
  { char: "🌶️", keywords: ["hot", "pepper", "spicy", "food"] },
  { char: "🫑", keywords: ["bell", "pepper", "vegetable", "food"] },
  { char: "🥒", keywords: ["cucumber", "vegetable", "food", "pickle"] },
  { char: "🥬", keywords: ["leafy", "green", "vegetable", "food"] },
  { char: "🥦", keywords: ["broccoli", "vegetable", "food", "green"] },
  { char: "🧄", keywords: ["garlic", "food", "cooking"] },
  { char: "🧅", keywords: ["onion", "food", "cooking", "vegetable"] },
  { char: "🍄", keywords: ["mushroom", "food", "fungus"] },
  { char: "🥜", keywords: ["peanuts", "food", "nuts"] },
  { char: "🌰", keywords: ["chestnut", "food", "nut"] },
  { char: "🍞", keywords: ["bread", "food", "loaf"] },
  { char: "🥐", keywords: ["croissant", "bread", "food", "french"] },
  { char: "🥖", keywords: ["baguette", "bread", "food", "french"] },
  { char: "🫓", keywords: ["flatbread", "bread", "food"] },
  { char: "🥨", keywords: ["pretzel", "bread", "food"] },
  { char: "🥯", keywords: ["bagel", "bread", "food"] },
  { char: "🥞", keywords: ["pancakes", "food", "breakfast"] },
  { char: "🧇", keywords: ["waffle", "food", "breakfast"] },
  { char: "🧀", keywords: ["cheese", "food", "dairy"] },
  { char: "🍖", keywords: ["meat", "bone", "food"] },
  { char: "🍗", keywords: ["poultry", "leg", "chicken", "food"] },
  { char: "🥩", keywords: ["cut", "meat", "steak", "food"] },
  { char: "🥓", keywords: ["bacon", "meat", "food", "breakfast"] },
  { char: "🍔", keywords: ["hamburger", "burger", "food", "fast food"] },
  { char: "🍟", keywords: ["french", "fries", "food", "fast food"] },
  { char: "🍕", keywords: ["pizza", "food", "italian"] },
  { char: "🌭", keywords: ["hot", "dog", "food", "sausage"] },
  { char: "🥪", keywords: ["sandwich", "food", "bread"] },
  { char: "🌮", keywords: ["taco", "food", "mexican"] },
  { char: "🌯", keywords: ["burrito", "food", "mexican", "wrap"] },
  { char: "🫔", keywords: ["tamale", "food", "mexican"] },
  { char: "🥙", keywords: ["stuffed", "flatbread", "food", "kebab"] },
  { char: "🧆", keywords: ["falafel", "food", "middle eastern"] },
  { char: "🥚", keywords: ["egg", "food", "breakfast"] },
  { char: "🍳", keywords: ["cooking", "egg", "fried", "food"] },
  { char: "🥘", keywords: ["shallow", "pan", "food", "paella"] },
  { char: "🍲", keywords: ["pot", "food", "stew", "soup"] },
  { char: "🫕", keywords: ["fondue", "food", "cheese"] },
  { char: "🥣", keywords: ["bowl", "spoon", "food", "cereal"] },
  { char: "🥗", keywords: ["green", "salad", "food", "healthy"] },
  { char: "🍿", keywords: ["popcorn", "food", "movie", "snack"] },
  { char: "🧈", keywords: ["butter", "food", "dairy"] },
  { char: "🧂", keywords: ["salt", "food", "seasoning"] },
  { char: "🥫", keywords: ["canned", "food", "can", "soup"] },
  { char: "🍱", keywords: ["bento", "box", "food", "japanese"] },
  { char: "🍘", keywords: ["rice", "cracker", "food", "japanese"] },
  { char: "🍙", keywords: ["rice", "ball", "food", "japanese"] },
  { char: "🍚", keywords: ["cooked", "rice", "food", "asian"] },
  { char: "🍛", keywords: ["curry", "rice", "food", "indian"] },
  { char: "🍜", keywords: ["steaming", "bowl", "noodles", "ramen"] },
  { char: "🍝", keywords: ["spaghetti", "pasta", "food", "italian"] },
  { char: "🍠", keywords: ["roasted", "sweet", "potato", "food"] },
  { char: "🍢", keywords: ["oden", "food", "japanese", "skewer"] },
  { char: "🍣", keywords: ["sushi", "food", "japanese", "fish"] },
  { char: "🍤", keywords: ["fried", "shrimp", "food", "tempura"] },
  { char: "🍥", keywords: ["fish", "cake", "swirl", "food"] },
  { char: "🥮", keywords: ["moon", "cake", "food", "chinese"] },
  { char: "🍡", keywords: ["dango", "food", "japanese", "sweet"] },
  { char: "🥟", keywords: ["dumpling", "food", "gyoza"] },
  { char: "🥠", keywords: ["fortune", "cookie", "food", "chinese"] },
  { char: "🥡", keywords: ["takeout", "box", "food", "chinese"] },
  { char: "🦀", keywords: ["crab", "food", "seafood"] },
  { char: "🦞", keywords: ["lobster", "food", "seafood"] },
  { char: "🦐", keywords: ["shrimp", "food", "seafood"] },
  { char: "🦑", keywords: ["squid", "food", "seafood"] },
  { char: "🦪", keywords: ["oyster", "food", "seafood"] },
  { char: "🍦", keywords: ["soft", "ice", "cream", "dessert"] },
  { char: "🍧", keywords: ["shaved", "ice", "dessert", "snow cone"] },
  { char: "🍨", keywords: ["ice", "cream", "dessert", "bowl"] },
  { char: "🍩", keywords: ["doughnut", "donut", "dessert", "sweet"] },
  { char: "🍪", keywords: ["cookie", "dessert", "sweet", "biscuit"] },
  { char: "🎂", keywords: ["birthday", "cake", "dessert", "celebration"] },
  { char: "🍰", keywords: ["shortcake", "cake", "dessert", "slice"] },
  { char: "🧁", keywords: ["cupcake", "cake", "dessert", "sweet"] },
  { char: "🥧", keywords: ["pie", "dessert", "food"] },
  { char: "🍫", keywords: ["chocolate", "bar", "sweet", "candy"] },
  { char: "🍬", keywords: ["candy", "sweet", "lollipop"] },
  { char: "🍭", keywords: ["lollipop", "candy", "sweet"] },
  { char: "🍮", keywords: ["custard", "pudding", "dessert", "flan"] },
  { char: "🍯", keywords: ["honey", "pot", "sweet", "bee"] },
  { char: "🍼", keywords: ["baby", "bottle", "milk", "infant"] },
  { char: "🥛", keywords: ["glass", "milk", "drink", "dairy"] },
  { char: "☕", keywords: ["coffee", "hot", "drink", "beverage"] },
  { char: "🫖", keywords: ["teapot", "tea", "drink"] },
  { char: "🍵", keywords: ["teacup", "tea", "drink", "green"] },
  { char: "🍶", keywords: ["sake", "drink", "japanese", "alcohol"] },
  { char: "🍾", keywords: ["champagne", "bottle", "popping", "celebration"] },
  { char: "🍷", keywords: ["wine", "glass", "drink", "alcohol"] },
  { char: "🍸", keywords: ["cocktail", "glass", "drink", "martini"] },
  { char: "🍹", keywords: ["tropical", "drink", "cocktail", "beach"] },
  { char: "🍺", keywords: ["beer", "mug", "drink", "alcohol"] },
  { char: "🍻", keywords: ["beers", "clinking", "cheers", "celebration"] },
  { char: "🥂", keywords: ["clinking", "glasses", "cheers", "celebration"] },
  { char: "🥃", keywords: ["tumbler", "glass", "whiskey", "alcohol"] },
  { char: "🥤", keywords: ["cup", "straw", "drink", "soda"] },
  { char: "🧋", keywords: ["bubble", "tea", "drink", "boba"] },
  { char: "🧃", keywords: ["beverage", "box", "juice", "drink"] },
  { char: "🧉", keywords: ["mate", "drink", "tea"] },
  { char: "🧊", keywords: ["ice", "cube", "cold"] },
  { char: "🥢", keywords: ["chopsticks", "utensils", "asian"] },
  { char: "🍽️", keywords: ["fork", "knife", "plate", "dining"] },
  { char: "🍴", keywords: ["fork", "knife", "utensils", "cutlery"] },
  { char: "🥄", keywords: ["spoon", "utensil", "cutlery"] },

  // Activities & Sports
  { char: "⚽", keywords: ["soccer", "ball", "football", "sport"] },
  { char: "🏀", keywords: ["basketball", "ball", "sport"] },
  { char: "🏈", keywords: ["american", "football", "ball", "sport"] },
  { char: "⚾", keywords: ["baseball", "ball", "sport"] },
  { char: "🥎", keywords: ["softball", "ball", "sport"] },
  { char: "🎾", keywords: ["tennis", "ball", "sport"] },
  { char: "🏐", keywords: ["volleyball", "ball", "sport"] },
  { char: "🏉", keywords: ["rugby", "football", "ball", "sport"] },
  { char: "🥏", keywords: ["flying", "disc", "frisbee", "sport"] },
  { char: "🎱", keywords: ["pool", "8", "ball", "billiards"] },
  { char: "🪀", keywords: ["yo-yo", "toy", "game"] },
  { char: "🏓", keywords: ["ping", "pong", "table tennis", "sport"] },
  { char: "🏸", keywords: ["badminton", "sport", "racket"] },
  { char: "🏒", keywords: ["ice", "hockey", "stick", "sport"] },
  { char: "🏑", keywords: ["field", "hockey", "stick", "sport"] },
  { char: "🥍", keywords: ["lacrosse", "sport", "stick"] },
  { char: "🏏", keywords: ["cricket", "game", "bat", "sport"] },
  { char: "🪃", keywords: ["boomerang", "weapon", "toy"] },
  { char: "🥅", keywords: ["goal", "net", "sport"] },
  { char: "⛳", keywords: ["flag", "hole", "golf", "sport"] },
  { char: "🪁", keywords: ["kite", "fly", "wind", "toy"] },
  { char: "🏹", keywords: ["bow", "arrow", "archery", "sport"] },
  { char: "🎣", keywords: ["fishing", "pole", "rod", "sport"] },
  { char: "🤿", keywords: ["diving", "mask", "snorkel", "underwater"] },
  { char: "🥊", keywords: ["boxing", "glove", "sport", "fight"] },
  { char: "🥋", keywords: ["martial", "arts", "uniform", "karate"] },
  { char: "🎽", keywords: ["running", "shirt", "sport", "marathon"] },
  { char: "🛹", keywords: ["skateboard", "sport", "skate"] },
  { char: "🛼", keywords: ["roller", "skate", "sport"] },
  { char: "🛷", keywords: ["sled", "snow", "winter", "sport"] },
  { char: "⛸️", keywords: ["ice", "skate", "winter", "sport"] },
  { char: "🥌", keywords: ["curling", "stone", "sport", "winter"] },
  { char: "🎿", keywords: ["ski", "snow", "sport", "winter"] },
  { char: "⛷️", keywords: ["skier", "snow", "sport", "winter"] },
  { char: "🏂", keywords: ["snowboarder", "snow", "sport", "winter"] },
  { char: "🪂", keywords: ["parachute", "skydiving", "sport"] },
  { char: "🏋️", keywords: ["weightlifter", "gym", "strong", "sport"] },
  { char: "🤼", keywords: ["wrestlers", "wrestling", "sport"] },
  { char: "🤸", keywords: ["person", "cartwheeling", "gymnastics", "sport"] },
  { char: "🤺", keywords: ["person", "fencing", "sport", "sword"] },
  { char: "🤾", keywords: ["person", "handball", "sport"] },
  { char: "🏌️", keywords: ["person", "golfing", "sport", "golf"] },
  { char: "🏇", keywords: ["horse", "racing", "jockey", "sport"] },
  { char: "🧘", keywords: ["person", "lotus", "yoga", "meditation"] },
  { char: "🏄", keywords: ["person", "surfing", "surf", "sport"] },
  { char: "🏊", keywords: ["person", "swimming", "swim", "sport"] },
  { char: "🤽", keywords: ["person", "water", "polo", "sport"] },
  { char: "🚣", keywords: ["person", "rowing", "boat", "sport"] },
  { char: "🧗", keywords: ["person", "climbing", "rock", "sport"] },
  { char: "🚴", keywords: ["person", "biking", "bicycle", "sport"] },
  { char: "🚵", keywords: ["person", "mountain", "biking", "sport"] },
  { char: "🤹", keywords: ["person", "juggling", "circus", "skill"] },
  { char: "🎪", keywords: ["circus", "tent", "entertainment"] },
  { char: "🎭", keywords: ["performing", "arts", "theater", "drama"] },
  { char: "🩰", keywords: ["ballet", "shoes", "dance"] },
  { char: "🎨", keywords: ["artist", "palette", "art", "paint"] },
  { char: "🎬", keywords: ["clapper", "board", "movie", "film"] },
  { char: "🎤", keywords: ["microphone", "sing", "karaoke", "music"] },
  { char: "🎧", keywords: ["headphone", "music", "listen"] },
  { char: "🎼", keywords: ["musical", "score", "music", "notes"] },
  { char: "🎹", keywords: ["musical", "keyboard", "piano", "music"] },
  { char: "🥁", keywords: ["drum", "music", "percussion"] },
  { char: "🪘", keywords: ["long", "drum", "music"] },
  { char: "🎷", keywords: ["saxophone", "music", "jazz"] },
  { char: "🎺", keywords: ["trumpet", "music", "brass"] },
  { char: "🪗", keywords: ["accordion", "music"] },
  { char: "🎸", keywords: ["guitar", "music", "rock"] },
  { char: "🪕", keywords: ["banjo", "music", "stringed"] },
  { char: "🎻", keywords: ["violin", "music", "stringed"] },
  { char: "🎲", keywords: ["game", "die", "dice", "gamble"] },
  { char: "♟️", keywords: ["chess", "pawn", "game"] },
  { char: "🎯", keywords: ["direct", "hit", "target", "bullseye"] },
  { char: "🎳", keywords: ["bowling", "game", "sport"] },
  { char: "🎮", keywords: ["video", "game", "controller", "gaming"] },
  { char: "🎰", keywords: ["slot", "machine", "gamble", "casino"] },
  { char: "🧩", keywords: ["puzzle", "piece", "jigsaw", "game"] },

  // Travel & Places
  { char: "🚗", keywords: ["car", "automobile", "vehicle", "drive"] },
  { char: "🚕", keywords: ["taxi", "cab", "car", "vehicle"] },
  { char: "🚙", keywords: ["sport", "utility", "vehicle", "suv"] },
  { char: "🚌", keywords: ["bus", "vehicle", "transportation"] },
  { char: "🚎", keywords: ["trolleybus", "bus", "vehicle"] },
  { char: "🏎️", keywords: ["racing", "car", "fast", "sport"] },
  { char: "🚓", keywords: ["police", "car", "vehicle", "cop"] },
  { char: "🚑", keywords: ["ambulance", "vehicle", "emergency", "medical"] },
  { char: "🚒", keywords: ["fire", "engine", "truck", "emergency"] },
  { char: "🚐", keywords: ["minibus", "van", "vehicle"] },
  { char: "🛻", keywords: ["pickup", "truck", "vehicle"] },
  { char: "🚚", keywords: ["delivery", "truck", "vehicle"] },
  { char: "🚛", keywords: ["articulated", "lorry", "truck", "vehicle"] },
  { char: "🚜", keywords: ["tractor", "vehicle", "farm"] },
  { char: "🏍️", keywords: ["motorcycle", "bike", "vehicle"] },
  { char: "🛵", keywords: ["motor", "scooter", "vehicle", "vespa"] },
  { char: "🦽", keywords: ["manual", "wheelchair", "accessibility"] },
  { char: "🦼", keywords: ["motorized", "wheelchair", "accessibility"] },
  { char: "🛺", keywords: ["auto", "rickshaw", "vehicle", "tuk tuk"] },
  { char: "🚲", keywords: ["bicycle", "bike", "cycle", "vehicle"] },
  { char: "🛴", keywords: ["kick", "scooter", "vehicle"] },
  { char: "🚏", keywords: ["bus", "stop", "transportation"] },
  { char: "🛣️", keywords: ["motorway", "highway", "road"] },
  { char: "🛤️", keywords: ["railway", "track", "train"] },
  { char: "🛢️", keywords: ["oil", "drum", "barrel", "fuel"] },
  { char: "⛽", keywords: ["fuel", "pump", "gas", "station"] },
  { char: "🚨", keywords: ["police", "car", "light", "siren"] },
  { char: "🚥", keywords: ["horizontal", "traffic", "light", "signal"] },
  { char: "🚦", keywords: ["vertical", "traffic", "light", "signal"] },
  { char: "🛑", keywords: ["stop", "sign", "octagon"] },
  { char: "🚧", keywords: ["construction", "warning", "barrier"] },
  { char: "⚓", keywords: ["anchor", "ship", "boat", "sea"] },
  { char: "⛵", keywords: ["sailboat", "boat", "yacht", "sailing"] },
  { char: "🛶", keywords: ["canoe", "boat", "kayak"] },
  { char: "🚤", keywords: ["speedboat", "boat", "fast", "motor"] },
  { char: "🛳️", keywords: ["passenger", "ship", "cruise", "boat"] },
  { char: "⛴️", keywords: ["ferry", "boat", "ship"] },
  { char: "🛥️", keywords: ["motor", "boat", "yacht"] },
  { char: "🚢", keywords: ["ship", "boat", "vessel"] },
  { char: "✈️", keywords: ["airplane", "plane", "flight", "travel"] },
  { char: "🛩️", keywords: ["small", "airplane", "plane"] },
  { char: "🛫", keywords: ["airplane", "departure", "takeoff", "flight"] },
  { char: "🛬", keywords: ["airplane", "arrival", "landing", "flight"] },
  { char: "🪂", keywords: ["parachute", "skydiving"] },
  { char: "💺", keywords: ["seat", "chair", "airplane"] },
  { char: "🚁", keywords: ["helicopter", "flight", "vehicle"] },
  { char: "🚟", keywords: ["suspension", "railway", "train"] },
  { char: "🚠", keywords: ["mountain", "cableway", "cable car"] },
  { char: "🚡", keywords: ["aerial", "tramway", "cable car"] },
  { char: "🛰️", keywords: ["satellite", "space", "communication"] },
  { char: "🚀", keywords: ["rocket", "space", "launch", "ship"] },
  { char: "🛸", keywords: ["flying", "saucer", "ufo", "alien"] },
  { char: "🛎️", keywords: ["bellhop", "bell", "hotel", "service"] },
  { char: "🧳", keywords: ["luggage", "suitcase", "travel", "baggage"] },
  { char: "⌛", keywords: ["hourglass", "done", "time", "sand"] },
  { char: "⏳", keywords: ["hourglass", "not", "done", "time"] },
  { char: "⌚", keywords: ["watch", "time", "clock"] },
  { char: "⏰", keywords: ["alarm", "clock", "time", "wake"] },
  { char: "⏱️", keywords: ["stopwatch", "time", "timer"] },
  { char: "⏲️", keywords: ["timer", "clock", "time"] },
  { char: "🕰️", keywords: ["mantelpiece", "clock", "time"] },
  { char: "🕛", keywords: ["twelve", "oclock", "time", "clock"] },
  { char: "🕧", keywords: ["twelve", "thirty", "time", "clock"] },
  { char: "🕐", keywords: ["one", "oclock", "time", "clock"] },
  { char: "🕜", keywords: ["one", "thirty", "time", "clock"] },
  { char: "🕑", keywords: ["two", "oclock", "time", "clock"] },
  { char: "🕝", keywords: ["two", "thirty", "time", "clock"] },
  { char: "🕒", keywords: ["three", "oclock", "time", "clock"] },
  { char: "🕞", keywords: ["three", "thirty", "time", "clock"] },
  { char: "🕓", keywords: ["four", "oclock", "time", "clock"] },
  { char: "🕟", keywords: ["four", "thirty", "time", "clock"] },
  { char: "🕔", keywords: ["five", "oclock", "time", "clock"] },
  { char: "🕠", keywords: ["five", "thirty", "time", "clock"] },
  { char: "🕕", keywords: ["six", "oclock", "time", "clock"] },
  { char: "🕡", keywords: ["six", "thirty", "time", "clock"] },
  { char: "🕖", keywords: ["seven", "oclock", "time", "clock"] },
  { char: "🕢", keywords: ["seven", "thirty", "time", "clock"] },
  { char: "🕗", keywords: ["eight", "oclock", "time", "clock"] },
  { char: "🕣", keywords: ["eight", "thirty", "time", "clock"] },
  { char: "🕘", keywords: ["nine", "oclock", "time", "clock"] },
  { char: "🕤", keywords: ["nine", "thirty", "time", "clock"] },
  { char: "🕙", keywords: ["ten", "oclock", "time", "clock"] },
  { char: "🕥", keywords: ["ten", "thirty", "time", "clock"] },
  { char: "🕚", keywords: ["eleven", "oclock", "time", "clock"] },
  { char: "🕦", keywords: ["eleven", "thirty", "time", "clock"] },
  { char: "🌑", keywords: ["new", "moon", "dark", "space"] },
  { char: "🌒", keywords: ["waxing", "crescent", "moon", "space"] },
  { char: "🌓", keywords: ["first", "quarter", "moon", "space"] },
  { char: "🌔", keywords: ["waxing", "gibbous", "moon", "space"] },
  { char: "🌕", keywords: ["full", "moon", "space", "night"] },
  { char: "🌖", keywords: ["waning", "gibbous", "moon", "space"] },
  { char: "🌗", keywords: ["last", "quarter", "moon", "space"] },
  { char: "🌘", keywords: ["waning", "crescent", "moon", "space"] },
  { char: "🌙", keywords: ["crescent", "moon", "night", "space"] },
  { char: "🌚", keywords: ["new", "moon", "face", "space"] },
  { char: "🌛", keywords: ["first", "quarter", "moon", "face"] },
  { char: "🌜", keywords: ["last", "quarter", "moon", "face"] },
  { char: "🌡️", keywords: ["thermometer", "temperature", "weather", "hot"] },
  { char: "☀️", keywords: ["sun", "sunny", "weather", "day"] },
  { char: "🌝", keywords: ["full", "moon", "face", "space"] },
  { char: "🌞", keywords: ["sun", "face", "sunny", "bright"] },
  { char: "🪐", keywords: ["ringed", "planet", "saturn", "space"] },
  { char: "⭐", keywords: ["star", "white", "medium", "space"] },
  { char: "🌟", keywords: ["glowing", "star", "sparkle", "space"] },
  { char: "🌠", keywords: ["shooting", "star", "night", "wish"] },
  { char: "🌌", keywords: ["milky", "way", "galaxy", "space"] },
  { char: "☁️", keywords: ["cloud", "weather", "sky"] },
  { char: "⛅", keywords: ["sun", "behind", "cloud", "weather"] },
  { char: "⛈️", keywords: ["cloud", "lightning", "rain", "storm"] },
  { char: "🌤️", keywords: ["sun", "small", "cloud", "weather"] },
  { char: "🌥️", keywords: ["sun", "behind", "large", "cloud"] },
  { char: "🌦️", keywords: ["sun", "behind", "rain", "cloud"] },
  { char: "🌧️", keywords: ["cloud", "rain", "weather"] },
  { char: "🌨️", keywords: ["cloud", "snow", "weather", "cold"] },
  { char: "🌩️", keywords: ["cloud", "lightning", "storm"] },
  { char: "🌪️", keywords: ["tornado", "weather", "storm"] },
  { char: "🌫️", keywords: ["fog", "weather", "cloud"] },
  { char: "🌬️", keywords: ["wind", "face", "blow"] },
  { char: "🌀", keywords: ["cyclone", "hurricane", "typhoon", "weather"] },
  { char: "🌈", keywords: ["rainbow", "rain", "colorful", "weather"] },
  { char: "🌂", keywords: ["closed", "umbrella", "rain", "weather"] },
  { char: "☂️", keywords: ["umbrella", "rain", "weather"] },
  { char: "☔", keywords: ["umbrella", "rain", "drops", "weather"] },
  { char: "⛱️", keywords: ["umbrella", "on", "ground", "beach"] },
  { char: "⚡", keywords: ["high", "voltage", "lightning", "electric"] },
  { char: "❄️", keywords: ["snowflake", "cold", "winter", "snow"] },
  { char: "☃️", keywords: ["snowman", "snow", "winter", "cold"] },
  { char: "⛄", keywords: ["snowman", "without", "snow", "winter"] },
  { char: "☄️", keywords: ["comet", "space", "shooting star"] },
  { char: "🔥", keywords: ["fire", "flame", "hot", "burn"] },
  { char: "💧", keywords: ["droplet", "water", "drop", "liquid"] },
  { char: "🌊", keywords: ["water", "wave", "ocean", "sea"] },

  // Objects
  { char: "🎃", keywords: ["jack", "o", "lantern", "halloween"] },
  { char: "🎄", keywords: ["christmas", "tree", "holiday", "xmas"] },
  { char: "🎆", keywords: ["fireworks", "celebration", "explosion"] },
  { char: "🎇", keywords: ["sparkler", "fireworks", "celebration"] },
  { char: "🧨", keywords: ["firecracker", "fireworks", "explosive"] },
  { char: "✨", keywords: ["sparkles", "shiny", "star", "magic"] },
  { char: "🎈", keywords: ["balloon", "party", "celebration"] },
  { char: "🎉", keywords: ["party", "popper", "celebration", "confetti"] },
  { char: "🎊", keywords: ["confetti", "ball", "party", "celebration"] },
  { char: "🎋", keywords: ["tanabata", "tree", "japanese", "wish"] },
  { char: "🎍", keywords: ["pine", "decoration", "japanese", "new year"] },
  { char: "🎎", keywords: ["japanese", "dolls", "festival", "hinamatsuri"] },
  { char: "🎏", keywords: ["carp", "streamer", "flag", "japanese"] },
  { char: "🎐", keywords: ["wind", "chime", "japanese", "bell"] },
  { char: "🎑", keywords: ["moon", "viewing", "ceremony", "japanese"] },
  { char: "🧧", keywords: ["red", "envelope", "gift", "money"] },
  { char: "🎀", keywords: ["ribbon", "bow", "gift", "decoration"] },
  { char: "🎁", keywords: ["wrapped", "gift", "present", "birthday"] },
  { char: "🎗️", keywords: ["reminder", "ribbon", "awareness"] },
  { char: "🎟️", keywords: ["admission", "tickets", "event", "pass"] },
  { char: "🎫", keywords: ["ticket", "admission", "event", "pass"] },
  { char: "🎖️", keywords: ["military", "medal", "award", "honor"] },
  { char: "🏆", keywords: ["trophy", "award", "win", "champion"] },
  { char: "🏅", keywords: ["sports", "medal", "award", "gold"] },
  { char: "🥇", keywords: ["first", "place", "medal", "gold", "winner"] },
  { char: "🥈", keywords: ["second", "place", "medal", "silver"] },
  { char: "🥉", keywords: ["third", "place", "medal", "bronze"] },
  { char: "⚽", keywords: ["soccer", "ball", "football", "sport"] },
  { char: "⚾", keywords: ["baseball", "sport", "ball"] },
  { char: "🥎", keywords: ["softball", "sport", "ball"] },
  { char: "🏀", keywords: ["basketball", "sport", "ball"] },
  { char: "🏐", keywords: ["volleyball", "sport", "ball"] },
  { char: "🏈", keywords: ["american", "football", "sport", "ball"] },
  { char: "🏉", keywords: ["rugby", "football", "sport", "ball"] },
  { char: "🎾", keywords: ["tennis", "sport", "ball"] },
  { char: "🥏", keywords: ["flying", "disc", "frisbee", "sport"] },
  { char: "🎳", keywords: ["bowling", "sport", "game"] },
  { char: "🏏", keywords: ["cricket", "game", "sport"] },
  { char: "🏑", keywords: ["field", "hockey", "sport"] },
  { char: "🏒", keywords: ["ice", "hockey", "sport"] },
  { char: "🥍", keywords: ["lacrosse", "sport", "stick"] },
  { char: "🏓", keywords: ["ping", "pong", "table tennis", "sport"] },
  { char: "🏸", keywords: ["badminton", "sport", "racket"] },
  { char: "🥊", keywords: ["boxing", "glove", "sport"] },
  { char: "🥋", keywords: ["martial", "arts", "uniform", "judo"] },
  { char: "🥅", keywords: ["goal", "net", "sport"] },
  { char: "⛳", keywords: ["flag", "in", "hole", "golf"] },
  { char: "⛸️", keywords: ["ice", "skate", "skating", "winter"] },
  { char: "🎣", keywords: ["fishing", "pole", "rod", "hobby"] },
  { char: "🤿", keywords: ["diving", "mask", "scuba", "underwater"] },
  { char: "🎽", keywords: ["running", "shirt", "sport", "athletic"] },
  { char: "🎿", keywords: ["skis", "skiing", "snow", "winter"] },
  { char: "🛷", keywords: ["sled", "sledding", "snow", "winter"] },
  { char: "🥌", keywords: ["curling", "stone", "sport", "ice"] },
  { char: "🎯", keywords: ["bullseye", "target", "dart", "accurate"] },
  { char: "🪀", keywords: ["yo-yo", "toy", "game"] },
  { char: "🪁", keywords: ["kite", "flying", "wind", "toy"] },
  { char: "🎱", keywords: ["pool", "8", "ball", "billiards"] },
  { char: "🔮", keywords: ["crystal", "ball", "fortune", "future"] },
  { char: "🪄", keywords: ["magic", "wand", "wizard", "spell"] },
  { char: "🧿", keywords: ["nazar", "amulet", "evil", "eye"] },
  { char: "🎮", keywords: ["video", "game", "controller", "gaming"] },
  { char: "🕹️", keywords: ["joystick", "game", "control", "arcade"] },
  { char: "🎰", keywords: ["slot", "machine", "gambling", "casino"] },
  { char: "🎲", keywords: ["game", "die", "dice", "random"] },
  { char: "🧩", keywords: ["puzzle", "piece", "jigsaw"] },
  { char: "🧸", keywords: ["teddy", "bear", "toy", "stuffed"] },
  { char: "🪅", keywords: ["pinata", "party", "celebration", "candy"] },
  { char: "🪆", keywords: ["nesting", "dolls", "russian", "matryoshka"] },
  { char: "♠️", keywords: ["spade", "suit", "card", "game"] },
  { char: "♥️", keywords: ["heart", "suit", "card", "game"] },
  { char: "♦️", keywords: ["diamond", "suit", "card", "game"] },
  { char: "♣️", keywords: ["club", "suit", "card", "game"] },
  { char: "♟️", keywords: ["chess", "pawn", "game", "piece"] },
  { char: "🃏", keywords: ["joker", "card", "game", "wild"] },
  { char: "🀄", keywords: ["mahjong", "red", "dragon", "game"] },
  { char: "🎴", keywords: ["flower", "playing", "cards", "japanese"] },
  { char: "🎭", keywords: ["performing", "arts", "theater", "masks"] },
  { char: "🖼️", keywords: ["framed", "picture", "art", "painting"] },
  { char: "🎨", keywords: ["artist", "palette", "paint", "art"] },
  { char: "🧵", keywords: ["thread", "sewing", "needle", "spool"] },
  { char: "🪡", keywords: ["sewing", "needle", "thread", "stitch"] },
  { char: "🧶", keywords: ["yarn", "knitting", "crochet", "ball"] },
  { char: "🪢", keywords: ["knot", "rope", "tie", "bind"] },

  // Symbols
  { char: "👓", keywords: ["glasses", "eyeglasses", "spectacles", "vision"] },
  { char: "🕶️", keywords: ["sunglasses", "cool", "shades", "dark"] },
  { char: "🥽", keywords: ["goggles", "eye", "protection", "safety"] },
  { char: "🥼", keywords: ["lab", "coat", "science", "doctor"] },
  { char: "🦺", keywords: ["safety", "vest", "construction", "warning"] },
  { char: "👔", keywords: ["necktie", "tie", "formal", "business"] },
  { char: "👕", keywords: ["t-shirt", "shirt", "clothing", "tshirt"] },
  { char: "👖", keywords: ["jeans", "pants", "clothing", "denim"] },
  { char: "🧣", keywords: ["scarf", "clothing", "winter", "neck"] },
  { char: "🧤", keywords: ["gloves", "hands", "winter", "warm"] },
  { char: "🧥", keywords: ["coat", "jacket", "clothing", "winter"] },
  { char: "🧦", keywords: ["socks", "feet", "clothing", "pair"] },
  { char: "👗", keywords: ["dress", "clothing", "woman", "fashion"] },
  { char: "👘", keywords: ["kimono", "japanese", "clothing", "traditional"] },
  { char: "🥻", keywords: ["sari", "clothing", "indian", "traditional"] },
  { char: "🩱", keywords: ["one-piece", "swimsuit", "bathing", "suit"] },
  { char: "🩲", keywords: ["briefs", "underwear", "clothing"] },
  { char: "🩳", keywords: ["shorts", "clothing", "pants"] },
  { char: "👙", keywords: ["bikini", "swimsuit", "beach", "swim"] },
  { char: "👚", keywords: ["womans", "clothes", "shirt", "blouse"] },
  { char: "👛", keywords: ["purse", "bag", "handbag", "wallet"] },
  { char: "👜", keywords: ["handbag", "bag", "purse", "fashion"] },
  { char: "👝", keywords: ["clutch", "bag", "purse", "pouch"] },
  { char: "🛍️", keywords: ["shopping", "bags", "purchase", "store"] },
  { char: "🎒", keywords: ["backpack", "school", "bag", "rucksack"] },
  { char: "🩴", keywords: ["thong", "sandal", "flip-flops", "beach"] },
  { char: "👞", keywords: ["mans", "shoe", "footwear", "dress"] },
  { char: "👟", keywords: ["running", "shoe", "sneaker", "athletic"] },
  { char: "🥾", keywords: ["hiking", "boot", "shoe", "outdoor"] },
  { char: "🥿", keywords: ["flat", "shoe", "ballet", "footwear"] },
  { char: "👠", keywords: ["high-heeled", "shoe", "heel", "fashion"] },
  { char: "👡", keywords: ["womans", "sandal", "shoe", "footwear"] },
  { char: "🩰", keywords: ["ballet", "shoes", "dance", "pointe"] },
  { char: "👢", keywords: ["womans", "boot", "shoe", "footwear"] },
  { char: "👑", keywords: ["crown", "king", "queen", "royal"] },
  { char: "👒", keywords: ["womans", "hat", "fashion", "sun"] },
  { char: "🎩", keywords: ["top", "hat", "formal", "magic"] },
  { char: "🎓", keywords: ["graduation", "cap", "student", "education"] },
  { char: "🧢", keywords: ["billed", "cap", "baseball", "hat"] },
  { char: "🪖", keywords: ["military", "helmet", "army", "soldier"] },
  { char: "⛑️", keywords: ["rescue", "worker", "helmet", "safety"] },
  { char: "📿", keywords: ["prayer", "beads", "rosary", "religion"] },
  { char: "💄", keywords: ["lipstick", "makeup", "cosmetics", "beauty"] },
  { char: "💍", keywords: ["ring", "diamond", "jewelry", "engagement"] },
  { char: "💎", keywords: ["gem", "stone", "diamond", "jewel"] },
  { char: "🔇", keywords: ["muted", "speaker", "sound", "silent"] },
  { char: "🔈", keywords: ["speaker", "low", "volume", "sound"] },
  { char: "🔉", keywords: ["speaker", "medium", "volume", "sound"] },
  { char: "🔊", keywords: ["speaker", "high", "volume", "loud"] },
  { char: "📢", keywords: ["loudspeaker", "announcement", "broadcast"] },
  { char: "📣", keywords: ["megaphone", "cheering", "announcement"] },
  { char: "📯", keywords: ["postal", "horn", "trumpet", "announcement"] },
  { char: "🔔", keywords: ["bell", "ring", "notification", "alarm"] },
  { char: "🔕", keywords: ["bell", "slash", "mute", "silent"] },
  { char: "🎼", keywords: ["musical", "score", "music", "notes"] },
  { char: "🎵", keywords: ["musical", "note", "music", "sound"] },
  { char: "🎶", keywords: ["musical", "notes", "music", "song"] },
  { char: "🎙️", keywords: ["studio", "microphone", "podcast", "recording"] },
  { char: "🎚️", keywords: ["level", "slider", "control", "adjust"] },
  { char: "🎛️", keywords: ["control", "knobs", "settings", "adjust"] },
  { char: "🎤", keywords: ["microphone", "sing", "karaoke", "music"] },
  { char: "🎧", keywords: ["headphone", "music", "listen", "audio"] },
  { char: "📻", keywords: ["radio", "broadcast", "music", "news"] },
  { char: "🎷", keywords: ["saxophone", "music", "jazz", "instrument"] },
  { char: "🪗", keywords: ["accordion", "music", "instrument"] },
  { char: "🎸", keywords: ["guitar", "music", "rock", "instrument"] },
  { char: "🎹", keywords: ["musical", "keyboard", "piano", "music"] },
  { char: "🎺", keywords: ["trumpet", "music", "brass", "instrument"] },
  { char: "🎻", keywords: ["violin", "music", "classical", "instrument"] },
  { char: "🪕", keywords: ["banjo", "music", "country", "instrument"] },
  { char: "🥁", keywords: ["drum", "music", "percussion", "beat"] },
  { char: "🪘", keywords: ["long", "drum", "music", "percussion"] },
  { char: "📱", keywords: ["mobile", "phone", "cell", "smartphone"] },
  { char: "📲", keywords: ["mobile", "phone", "arrow", "call"] },
  { char: "☎️", keywords: ["telephone", "phone", "call", "landline"] },
  { char: "📞", keywords: ["telephone", "receiver", "phone", "call"] },
  { char: "📟", keywords: ["pager", "beeper", "communication"] },
  { char: "📠", keywords: ["fax", "machine", "document", "send"] },
  { char: "🔋", keywords: ["battery", "power", "energy", "charge"] },
  { char: "🔌", keywords: ["electric", "plug", "power", "electricity"] },
  { char: "💻", keywords: ["laptop", "computer", "pc", "technology"] },
  { char: "🖥️", keywords: ["desktop", "computer", "pc", "monitor"] },
  { char: "🖨️", keywords: ["printer", "print", "document", "office"] },
  { char: "⌨️", keywords: ["keyboard", "type", "computer", "input"] },
  { char: "🖱️", keywords: ["computer", "mouse", "click", "pointer"] },
  { char: "🖲️", keywords: ["trackball", "mouse", "computer", "input"] },
  { char: "💽", keywords: ["computer", "disk", "minidisc", "storage"] },
  { char: "💾", keywords: ["floppy", "disk", "save", "storage"] },
  { char: "💿", keywords: ["optical", "disk", "cd", "storage"] },
  { char: "📀", keywords: ["dvd", "disk", "movie", "storage"] },
  { char: "🧮", keywords: ["abacus", "calculation", "math", "counting"] },
  { char: "🎥", keywords: ["movie", "camera", "film", "video"] },
  { char: "🎞️", keywords: ["film", "frames", "movie", "cinema"] },
  { char: "📽️", keywords: ["film", "projector", "movie", "cinema"] },
  { char: "🎬", keywords: ["clapper", "board", "movie", "action"] },
  { char: "📺", keywords: ["television", "tv", "screen", "watch"] },
  { char: "📷", keywords: ["camera", "photo", "picture", "photography"] },
  { char: "📸", keywords: ["camera", "flash", "photo", "picture"] },
  { char: "📹", keywords: ["video", "camera", "record", "film"] },
  { char: "📼", keywords: ["videocassette", "vhs", "tape", "retro"] },
  { char: "🔎", keywords: ["magnifying", "glass", "right", "search"] },
  { char: "🕯️", keywords: ["candle", "light", "flame", "wax"] },
  { char: "💡", keywords: ["light", "bulb", "idea", "bright"] },
  { char: "🔦", keywords: ["flashlight", "torch", "light", "dark"] },
  { char: "🏮", keywords: ["red", "paper", "lantern", "japanese"] },
  { char: "🪔", keywords: ["diya", "lamp", "oil", "light"] },
  { char: "📔", keywords: ["notebook", "decorative", "cover", "journal"] },
  { char: "📕", keywords: ["closed", "book", "read", "library"] },
  { char: "📖", keywords: ["open", "book", "read", "study"] },
  { char: "📗", keywords: ["green", "book", "read", "library"] },
  { char: "📘", keywords: ["blue", "book", "read", "library"] },
  { char: "📙", keywords: ["orange", "book", "read", "library"] },
  { char: "📚", keywords: ["books", "stack", "library", "study"] },
  { char: "📓", keywords: ["notebook", "journal", "write", "notes"] },
  { char: "📒", keywords: ["ledger", "notebook", "accounting", "book"] },
  { char: "📃", keywords: ["page", "curl", "document", "paper"] },
  { char: "📜", keywords: ["scroll", "paper", "document", "ancient"] },
  { char: "📄", keywords: ["page", "facing", "up", "document"] },
  { char: "📰", keywords: ["newspaper", "news", "press", "media"] },
  { char: "🗞️", keywords: ["rolled", "newspaper", "news", "paper"] },
  { char: "📑", keywords: ["bookmark", "tabs", "organize", "mark"] },
  { char: "🔖", keywords: ["bookmark", "tag", "mark", "save"] },
  { char: "🏷️", keywords: ["label", "tag", "price", "mark"] },
  { char: "💰", keywords: ["money", "bag", "dollar", "cash"] },
  { char: "🪙", keywords: ["coin", "money", "currency", "metal"] },
  { char: "💴", keywords: ["yen", "banknote", "money", "japanese"] },
  { char: "💵", keywords: ["dollar", "banknote", "money", "cash"] },
  { char: "💶", keywords: ["euro", "banknote", "money", "currency"] },
  { char: "💷", keywords: ["pound", "banknote", "money", "british"] },
  { char: "💸", keywords: ["money", "wings", "fly", "spend"] },
  { char: "💳", keywords: ["credit", "card", "payment", "money"] },
  { char: "🧾", keywords: ["receipt", "bill", "payment", "proof"] },
  { char: "💹", keywords: ["chart", "increasing", "yen", "trend"] },
  { char: "✉️", keywords: ["envelope", "mail", "letter", "message"] },
  { char: "📧", keywords: ["email", "mail", "message", "electronic"] },
  { char: "📨", keywords: ["incoming", "envelope", "mail", "receive"] },
  { char: "📩", keywords: ["envelope", "arrow", "mail", "send"] },
  { char: "📤", keywords: ["outbox", "tray", "mail", "send"] },
  { char: "📥", keywords: ["inbox", "tray", "mail", "receive"] },
  { char: "📦", keywords: ["package", "box", "parcel", "delivery"] },
  { char: "📫", keywords: ["closed", "mailbox", "flag", "mail"] },
  { char: "📪", keywords: ["closed", "mailbox", "lowered", "flag"] },
  { char: "📬", keywords: ["open", "mailbox", "raised", "flag"] },
  { char: "📭", keywords: ["open", "mailbox", "lowered", "flag"] },
  { char: "📮", keywords: ["postbox", "mail", "post", "letter"] },
  { char: "🗳️", keywords: ["ballot", "box", "vote", "election"] },
  { char: "✏️", keywords: ["pencil", "write", "draw", "edit"] },
  { char: "✒️", keywords: ["black", "nib", "pen", "write"] },
  { char: "🖋️", keywords: ["fountain", "pen", "write", "ink"] },
  { char: "🖊️", keywords: ["pen", "write", "ballpoint"] },
  { char: "🖌️", keywords: ["paintbrush", "art", "paint", "draw"] },
  { char: "🖍️", keywords: ["crayon", "draw", "color", "art"] },
  { char: "📝", keywords: ["memo", "note", "write", "pencil"] },
  { char: "💼", keywords: ["briefcase", "business", "work", "bag"] },
  { char: "📁", keywords: ["file", "folder", "organize", "directory"] },
  { char: "📂", keywords: ["open", "file", "folder", "directory"] },
  { char: "🗂️", keywords: ["card", "index", "dividers", "organize"] },
  { char: "📅", keywords: ["calendar", "date", "schedule", "day"] },
  { char: "📆", keywords: ["tear-off", "calendar", "date", "schedule"] },
  { char: "🗒️", keywords: ["spiral", "notepad", "note", "write"] },
  { char: "🗓️", keywords: ["spiral", "calendar", "date", "schedule"] },
  { char: "📇", keywords: ["card", "index", "rolodex", "contacts"] },
  { char: "📈", keywords: ["chart", "increasing", "trend", "growth"] },
  { char: "📉", keywords: ["chart", "decreasing", "trend", "decline"] },
  { char: "📊", keywords: ["bar", "chart", "graph", "statistics"] },
  { char: "📋", keywords: ["clipboard", "copy", "paste", "document"] },
  { char: "📌", keywords: ["pushpin", "pin", "tack", "mark"] },
  { char: "📍", keywords: ["round", "pushpin", "location", "map"] },
  { char: "📎", keywords: ["paperclip", "attach", "clip", "link"] },
  { char: "🖇️", keywords: ["linked", "paperclips", "attach", "connect"] },
  { char: "📏", keywords: ["straight", "ruler", "measure", "length"] },
  { char: "📐", keywords: ["triangular", "ruler", "measure", "angle"] },
  { char: "✂️", keywords: ["scissors", "cut", "snip", "trim"] },
  { char: "🗃️", keywords: ["card", "file", "box", "storage"] },
  { char: "🗄️", keywords: ["file", "cabinet", "storage", "organize"] },
  { char: "🗑️", keywords: ["wastebasket", "trash", "garbage", "delete"] },
  { char: "🔒", keywords: ["locked", "secure", "private", "closed"] },
  { char: "🔓", keywords: ["unlocked", "open", "unsecure", "access"] },
  { char: "🔏", keywords: ["locked", "pen", "secure", "write"] },
  { char: "🔐", keywords: ["locked", "key", "secure", "closed"] },
  { char: "🔑", keywords: ["key", "unlock", "access", "open"] },
  { char: "🗝️", keywords: ["old", "key", "antique", "unlock"] },
  { char: "🔨", keywords: ["hammer", "tool", "build", "nail"] },
  { char: "🪓", keywords: ["axe", "tool", "chop", "wood"] },
  { char: "⛏️", keywords: ["pick", "tool", "mining", "dig"] },
  { char: "⚒️", keywords: ["hammer", "pick", "tools", "build"] },
  { char: "🛠️", keywords: ["hammer", "wrench", "tools", "fix"] },
  { char: "🗡️", keywords: ["dagger", "knife", "weapon", "blade"] },
  { char: "⚔️", keywords: ["crossed", "swords", "battle", "fight"] },
  { char: "🔫", keywords: ["pistol", "gun", "water", "toy"] },
  { char: "🪃", keywords: ["boomerang", "weapon", "throw", "return"] },
  { char: "🏹", keywords: ["bow", "arrow", "archery", "weapon"] },
  { char: "🛡️", keywords: ["shield", "protection", "defend", "guard"] },
  { char: "🪚", keywords: ["carpentry", "saw", "tool", "cut"] },
  { char: "🔧", keywords: ["wrench", "tool", "fix", "mechanic"] },
  { char: "🪛", keywords: ["screwdriver", "tool", "fix", "screw"] },
  { char: "🔩", keywords: ["nut", "bolt", "screw", "hardware"] },
  { char: "⚙️", keywords: ["gear", "settings", "cog", "mechanical"] },
  { char: "🗜️", keywords: ["compression", "clamp", "tool", "squeeze"] },
  { char: "⚖️", keywords: ["balance", "scale", "justice", "law"] },
  { char: "🦯", keywords: ["white", "cane", "probing", "accessibility"] },
  { char: "🔗", keywords: ["link", "chain", "connect", "url"] },
  { char: "⛓️", keywords: ["chains", "link", "metal", "connect"] },
  { char: "🪝", keywords: ["hook", "catch", "fishing", "hang"] },
  { char: "🧰", keywords: ["toolbox", "tools", "repair", "fix"] },
  { char: "🧲", keywords: ["magnet", "attract", "magnetic", "pull"] },
  { char: "🪜", keywords: ["ladder", "climb", "step", "up"] },
  { char: "⚗️", keywords: ["alembic", "chemistry", "science", "lab"] },
  { char: "🧪", keywords: ["test", "tube", "science", "chemistry"] },
  { char: "🧫", keywords: ["petri", "dish", "biology", "bacteria"] },
  { char: "🧬", keywords: ["dna", "genetics", "biology", "science"] },
  { char: "🔬", keywords: ["microscope", "science", "lab", "research"] },
  { char: "🔭", keywords: ["telescope", "space", "astronomy", "stars"] },
  { char: "📡", keywords: ["satellite", "antenna", "dish", "signal"] },
  { char: "💉", keywords: ["syringe", "needle", "shot", "vaccine"] },
  { char: "🩸", keywords: ["drop", "blood", "donation", "medical"] },
  { char: "💊", keywords: ["pill", "medicine", "drug", "medication"] },
  { char: "🩹", keywords: ["adhesive", "bandage", "first aid", "injury"] },
  { char: "🩺", keywords: ["stethoscope", "doctor", "medical", "heart"] },
  { char: "🚪", keywords: ["door", "entrance", "exit", "entry"] },
  { char: "🛗", keywords: ["elevator", "lift", "up", "down"] },
  { char: "🪞", keywords: ["mirror", "reflection", "look", "glass"] },
  { char: "🪟", keywords: ["window", "glass", "view", "opening"] },
  { char: "🛏️", keywords: ["bed", "sleep", "rest", "bedroom"] },
  { char: "🛋️", keywords: ["couch", "lamp", "sofa", "furniture"] },
  { char: "🪑", keywords: ["chair", "seat", "sit", "furniture"] },
  { char: "🚽", keywords: ["toilet", "bathroom", "wc", "restroom"] },
  { char: "🪠", keywords: ["plunger", "toilet", "bathroom", "unclog"] },
  { char: "🚿", keywords: ["shower", "bath", "clean", "water"] },
  { char: "🛁", keywords: ["bathtub", "bath", "tub", "clean"] },
  { char: "🪤", keywords: ["mouse", "trap", "catch", "rodent"] },
  { char: "🪒", keywords: ["razor", "shave", "blade", "grooming"] },
  { char: "🧴", keywords: ["lotion", "bottle", "soap", "shampoo"] },
  { char: "🧷", keywords: ["safety", "pin", "diaper", "fasten"] },
  { char: "🧹", keywords: ["broom", "sweep", "clean", "witch"] },
  { char: "🧺", keywords: ["basket", "laundry", "picnic", "wicker"] },
  { char: "🧻", keywords: ["roll", "paper", "toilet", "tissue"] },
  { char: "🪣", keywords: ["bucket", "pail", "water", "container"] },
  { char: "🧼", keywords: ["soap", "wash", "clean", "bar"] },
  { char: "🪥", keywords: ["toothbrush", "brush", "teeth", "dental"] },
  { char: "🧽", keywords: ["sponge", "clean", "wash", "scrub"] },
  { char: "🧯", keywords: ["fire", "extinguisher", "safety", "emergency"] },
  { char: "🛒", keywords: ["shopping", "cart", "trolley", "store"] },
  { char: "🚬", keywords: ["cigarette", "smoking", "smoke", "tobacco"] },
  { char: "⚰️", keywords: ["coffin", "death", "funeral", "casket"] },
  { char: "🪦", keywords: ["headstone", "grave", "cemetery", "tombstone"] },
  { char: "⚱️", keywords: ["funeral", "urn", "ashes", "death"] },
  { char: "🗿", keywords: ["moai", "easter", "island", "statue"] },
  { char: "🪧", keywords: ["placard", "sign", "protest", "notice"] },

  // Flags & Symbols
  { char: "🏧", keywords: ["atm", "sign", "bank", "money"] },
  { char: "🚮", keywords: ["litter", "bin", "sign", "trash"] },
  { char: "🚰", keywords: ["potable", "water", "drinking", "fountain"] },
  { char: "♿", keywords: ["wheelchair", "symbol", "accessible", "disabled"] },
  { char: "🚹", keywords: ["mens", "room", "bathroom", "male"] },
  { char: "🚺", keywords: ["womens", "room", "bathroom", "female"] },
  { char: "🚻", keywords: ["restroom", "bathroom", "toilet", "wc"] },
  { char: "🚼", keywords: ["baby", "symbol", "infant", "changing"] },
  { char: "🚾", keywords: ["water", "closet", "wc", "toilet"] },
  { char: "🛂", keywords: ["passport", "control", "customs", "border"] },
  { char: "🛃", keywords: ["customs", "baggage", "claim", "airport"] },
  { char: "🛄", keywords: ["baggage", "claim", "luggage", "airport"] },
  { char: "🛅", keywords: ["left", "luggage", "baggage", "storage"] },
  { char: "⚠️", keywords: ["warning", "caution", "alert", "danger"] },
  { char: "🚸", keywords: ["children", "crossing", "school", "kids"] },
  { char: "⛔", keywords: ["no", "entry", "stop", "prohibited"] },
  { char: "🚫", keywords: ["prohibited", "forbidden", "no", "ban"] },
  { char: "🚳", keywords: ["no", "bicycles", "bike", "prohibited"] },
  { char: "🚭", keywords: ["no", "smoking", "cigarette", "prohibited"] },
  { char: "🚯", keywords: ["no", "littering", "trash", "prohibited"] },
  { char: "🚱", keywords: ["non-potable", "water", "not", "drinkable"] },
  { char: "🚷", keywords: ["no", "pedestrians", "walk", "prohibited"] },
  { char: "📵", keywords: ["no", "mobile", "phones", "cell"] },
  { char: "🔞", keywords: ["no", "one", "under", "eighteen"] },
  { char: "☢️", keywords: ["radioactive", "nuclear", "danger", "hazard"] },
  { char: "☣️", keywords: ["biohazard", "danger", "toxic", "hazard"] },
  { char: "⬆️", keywords: ["up", "arrow", "north", "direction"] },
  { char: "↗️", keywords: ["up-right", "arrow", "northeast", "direction"] },
  { char: "➡️", keywords: ["right", "arrow", "east", "direction"] },
  { char: "↘️", keywords: ["down-right", "arrow", "southeast", "direction"] },
  { char: "⬇️", keywords: ["down", "arrow", "south", "direction"] },
  { char: "↙️", keywords: ["down-left", "arrow", "southwest", "direction"] },
  { char: "⬅️", keywords: ["left", "arrow", "west", "direction"] },
  { char: "↖️", keywords: ["up-left", "arrow", "northwest", "direction"] },
  { char: "↕️", keywords: ["up-down", "arrow", "vertical", "direction"] },
  { char: "↔️", keywords: ["left-right", "arrow", "horizontal", "direction"] },
  { char: "↩️", keywords: ["right", "arrow", "curving", "left"] },
  { char: "↪️", keywords: ["left", "arrow", "curving", "right"] },
  { char: "⤴️", keywords: ["right", "arrow", "curving", "up"] },
  { char: "⤵️", keywords: ["right", "arrow", "curving", "down"] },
  { char: "🔃", keywords: ["clockwise", "arrows", "reload", "refresh"] },
  { char: "🔄", keywords: ["counterclockwise", "arrows", "reload", "refresh"] },
  { char: "🔙", keywords: ["back", "arrow", "return", "previous"] },
  { char: "🔚", keywords: ["end", "arrow", "finish", "last"] },
  { char: "🔛", keywords: ["on", "arrow", "active", "enabled"] },
  { char: "🔜", keywords: ["soon", "arrow", "coming", "next"] },
  { char: "🔝", keywords: ["top", "arrow", "up", "best"] },
  { char: "🛐", keywords: ["place", "worship", "religion", "prayer"] },
  { char: "⚛️", keywords: ["atom", "symbol", "science", "physics"] },
  { char: "🕉️", keywords: ["om", "hinduism", "religion", "sacred"] },
  { char: "✡️", keywords: ["star", "david", "judaism", "jewish"] },
  { char: "☸️", keywords: ["wheel", "dharma", "buddhism", "religion"] },
  { char: "☯️", keywords: ["yin", "yang", "balance", "taoism"] },
  { char: "✝️", keywords: ["latin", "cross", "christianity", "religion"] },
  { char: "☦️", keywords: ["orthodox", "cross", "christianity", "religion"] },
  { char: "☪️", keywords: ["star", "crescent", "islam", "muslim"] },
  { char: "☮️", keywords: ["peace", "symbol", "hippie", "love"] },
  { char: "🕎", keywords: ["menorah", "judaism", "candelabrum", "hanukkah"] },
  { char: "🔯", keywords: ["dotted", "six-pointed", "star", "fortune"] },
  { char: "♈", keywords: ["aries", "zodiac", "ram", "astrology"] },
  { char: "♉", keywords: ["taurus", "zodiac", "bull", "astrology"] },
  { char: "♊", keywords: ["gemini", "zodiac", "twins", "astrology"] },
  { char: "♋", keywords: ["cancer", "zodiac", "crab", "astrology"] },
  { char: "♌", keywords: ["leo", "zodiac", "lion", "astrology"] },
  { char: "♍", keywords: ["virgo", "zodiac", "maiden", "astrology"] },
  { char: "♎", keywords: ["libra", "zodiac", "scales", "astrology"] },
  { char: "♏", keywords: ["scorpio", "zodiac", "scorpion", "astrology"] },
  { char: "♐", keywords: ["sagittarius", "zodiac", "archer", "astrology"] },
  { char: "♑", keywords: ["capricorn", "zodiac", "goat", "astrology"] },
  { char: "♒", keywords: ["aquarius", "zodiac", "water", "astrology"] },
  { char: "♓", keywords: ["pisces", "zodiac", "fish", "astrology"] },
  { char: "⛎", keywords: ["ophiuchus", "zodiac", "serpent", "bearer"] },
  { char: "🔀", keywords: ["shuffle", "tracks", "button", "random"] },
  { char: "🔁", keywords: ["repeat", "button", "loop", "again"] },
  { char: "🔂", keywords: ["repeat", "single", "button", "one"] },
  { char: "▶️", keywords: ["play", "button", "start", "media"] },
  { char: "⏩", keywords: ["fast-forward", "button", "skip", "media"] },
  { char: "⏭️", keywords: ["next", "track", "button", "skip"] },
  { char: "⏯️", keywords: ["play", "pause", "button", "media"] },
  { char: "◀️", keywords: ["reverse", "button", "back", "media"] },
  { char: "⏪", keywords: ["fast", "reverse", "button", "rewind"] },
  { char: "⏮️", keywords: ["last", "track", "button", "previous"] },
  { char: "🔼", keywords: ["upwards", "button", "up", "triangle"] },
  { char: "⏫", keywords: ["fast", "up", "button", "double"] },
  { char: "🔽", keywords: ["downwards", "button", "down", "triangle"] },
  { char: "⏬", keywords: ["fast", "down", "button", "double"] },
  { char: "⏸️", keywords: ["pause", "button", "stop", "media"] },
  { char: "⏹️", keywords: ["stop", "button", "end", "media"] },
  { char: "⏺️", keywords: ["record", "button", "rec", "media"] },
  { char: "⏏️", keywords: ["eject", "button", "remove", "media"] },
  { char: "🎦", keywords: ["cinema", "movie", "film", "theater"] },
  { char: "🔅", keywords: ["dim", "button", "brightness", "low"] },
  { char: "🔆", keywords: ["bright", "button", "brightness", "high"] },
  { char: "📶", keywords: ["antenna", "bars", "signal", "reception"] },
  { char: "📳", keywords: ["vibration", "mode", "silent", "phone"] },
  { char: "📴", keywords: ["mobile", "phone", "off", "power"] },
  { char: "♀️", keywords: ["female", "sign", "woman", "venus"] },
  { char: "♂️", keywords: ["male", "sign", "man", "mars"] },
  { char: "⚧️", keywords: ["transgender", "symbol", "trans", "gender"] },
  { char: "➕", keywords: ["plus", "add", "more", "positive"] },
  { char: "➖", keywords: ["minus", "subtract", "less", "negative"] },
  { char: "➗", keywords: ["divide", "division", "math", "split"] },
  { char: "♾️", keywords: ["infinity", "forever", "unlimited", "endless"] },
  { char: "‼️", keywords: ["double", "exclamation", "mark", "emphasis"] },
  { char: "⁉️", keywords: ["exclamation", "question", "mark", "surprise"] },
  { char: "❓", keywords: ["question", "mark", "red", "help"] },
  { char: "❔", keywords: ["white", "question", "mark", "help"] },
  { char: "❕", keywords: ["white", "exclamation", "mark", "emphasis"] },
  { char: "❗", keywords: ["exclamation", "mark", "red", "important"] },
  { char: "〰️", keywords: ["wavy", "dash", "line", "wave"] },
  { char: "💱", keywords: ["currency", "exchange", "money", "forex"] },
  { char: "💲", keywords: ["heavy", "dollar", "sign", "money"] },
  { char: "⚕️", keywords: ["medical", "symbol", "health", "caduceus"] },
  { char: "♻️", keywords: ["recycling", "symbol", "reuse", "eco"] },
  { char: "⚜️", keywords: ["fleur-de-lis", "symbol", "french", "royal"] },
  { char: "🔱", keywords: ["trident", "emblem", "pitchfork", "poseidon"] },
  { char: "📛", keywords: ["name", "badge", "tag", "identification"] },
  { char: "🔰", keywords: ["japanese", "beginner", "symbol", "new"] },
  { char: "⭕", keywords: ["hollow", "red", "circle", "o"] },
  { char: "✅", keywords: ["check", "mark", "button", "correct"] },
  { char: "☑️", keywords: ["check", "box", "mark", "tick"] },
  { char: "✔️", keywords: ["check", "mark", "tick", "correct"] },
  { char: "❌", keywords: ["cross", "mark", "x", "wrong"] },
  { char: "❎", keywords: ["cross", "mark", "button", "x"] },
  { char: "➰", keywords: ["curly", "loop", "swirl", "curl"] },
  { char: "➿", keywords: ["double", "curly", "loop", "swirl"] },
  { char: "〽️", keywords: ["part", "alternation", "mark", "japanese"] },
  { char: "✳️", keywords: ["eight-spoked", "asterisk", "star", "symbol"] },
  { char: "✴️", keywords: ["eight-pointed", "star", "orange", "symbol"] },
  { char: "❇️", keywords: ["sparkle", "star", "shiny", "symbol"] },
  { char: "©️", keywords: ["copyright", "symbol", "protected", "rights"] },
  { char: "®️", keywords: ["registered", "trademark", "symbol", "brand"] },
  { char: "™️", keywords: ["trade", "mark", "symbol", "brand"] },

  { char: "™️", keywords: ["trade", "mark", "symbol", "trademark"] },
  { char: "#️⃣", keywords: ["keycap", "hash", "number", "pound"] },
  { char: "*️⃣", keywords: ["keycap", "asterisk", "star", "multiply"] },
  { char: "0️⃣", keywords: ["keycap", "zero", "number", "0"] },
  { char: "1️⃣", keywords: ["keycap", "one", "number", "1"] },
  { char: "2️⃣", keywords: ["keycap", "two", "number", "2"] },
  { char: "3️⃣", keywords: ["keycap", "three", "number", "3"] },
  { char: "4️⃣", keywords: ["keycap", "four", "number", "4"] },
  { char: "5️⃣", keywords: ["keycap", "five", "number", "5"] },
  { char: "6️⃣", keywords: ["keycap", "six", "number", "6"] },
  { char: "7️⃣", keywords: ["keycap", "seven", "number", "7"] },
  { char: "8️⃣", keywords: ["keycap", "eight", "number", "8"] },
  { char: "9️⃣", keywords: ["keycap", "nine", "number", "9"] },
  { char: "🔟", keywords: ["keycap", "ten", "number", "10"] },
  { char: "🔠", keywords: ["input", "latin", "uppercase", "letters"] },
  { char: "🔡", keywords: ["input", "latin", "lowercase", "letters"] },
  { char: "🔢", keywords: ["input", "numbers", "digits", "1234"] },
  { char: "🔣", keywords: ["input", "symbols", "characters", "special"] },
  { char: "🔤", keywords: ["input", "latin", "letters", "abc"] },
  { char: "🅰️", keywords: ["a", "button", "blood", "type"] },
  { char: "🆎", keywords: ["ab", "button", "blood", "type"] },
  { char: "🅱️", keywords: ["b", "button", "blood", "type"] },
  { char: "🆑", keywords: ["cl", "button", "clear", "symbol"] },
  { char: "🆒", keywords: ["cool", "button", "awesome", "word"] },
  { char: "🆓", keywords: ["free", "button", "no", "cost"] },
  { char: "ℹ️", keywords: ["information", "info", "i", "details"] },
  { char: "🆔", keywords: ["id", "button", "identification", "identity"] },
  { char: "Ⓜ️", keywords: ["circled", "m", "metro", "subway"] },
  { char: "🆕", keywords: ["new", "button", "fresh", "latest"] },
  { char: "🆖", keywords: ["ng", "button", "no", "good"] },
  { char: "🅾️", keywords: ["o", "button", "blood", "type"] },
  { char: "🆗", keywords: ["ok", "button", "okay", "good"] },
  { char: "🅿️", keywords: ["p", "button", "parking", "letter"] },
  { char: "🆘", keywords: ["sos", "button", "help", "emergency"] },
  { char: "🆙", keywords: ["up", "button", "level", "increase"] },
  { char: "🆚", keywords: ["vs", "button", "versus", "against"] },
  { char: "🈁", keywords: ["japanese", "here", "katakana", "koko"] },
  { char: "🈂️", keywords: ["japanese", "service", "charge", "katakana"] },
  { char: "🈷️", keywords: ["japanese", "monthly", "amount", "kanji"] },
  { char: "🈶", keywords: ["japanese", "not", "free", "charge"] },
  { char: "🈯", keywords: ["japanese", "reserved", "kanji", "finger"] },
  { char: "🉐", keywords: ["japanese", "bargain", "kanji", "deal"] },
  { char: "🈹", keywords: ["japanese", "discount", "kanji", "sale"] },
  { char: "🈚", keywords: ["japanese", "free", "charge", "kanji"] },
  { char: "🈲", keywords: ["japanese", "prohibited", "kanji", "forbidden"] },
  { char: "🉑", keywords: ["japanese", "acceptable", "kanji", "ok"] },
  { char: "🈸", keywords: ["japanese", "application", "kanji", "form"] },
  { char: "🈴", keywords: ["japanese", "passing", "grade", "kanji"] },
  { char: "🈳", keywords: ["japanese", "vacancy", "kanji", "empty"] },
  {
    char: "㊗️",
    keywords: ["japanese", "congratulations", "kanji", "celebrate"],
  },
  { char: "㊙️", keywords: ["japanese", "secret", "kanji", "hidden"] },
  { char: "🈺", keywords: ["japanese", "open", "business", "kanji"] },
  { char: "🈵", keywords: ["japanese", "no", "vacancy", "full"] },
  { char: "🔴", keywords: ["red", "circle", "round", "dot"] },
  { char: "🟠", keywords: ["orange", "circle", "round", "dot"] },
  { char: "🟡", keywords: ["yellow", "circle", "round", "dot"] },
  { char: "🟢", keywords: ["green", "circle", "round", "dot"] },
  { char: "🔵", keywords: ["blue", "circle", "round", "dot"] },
  { char: "🟣", keywords: ["purple", "circle", "round", "dot"] },
  { char: "🟤", keywords: ["brown", "circle", "round", "dot"] },
  { char: "⚫", keywords: ["black", "circle", "round", "dot"] },
  { char: "⚪", keywords: ["white", "circle", "round", "dot"] },
  { char: "🟥", keywords: ["red", "square", "block", "shape"] },
  { char: "🟧", keywords: ["orange", "square", "block", "shape"] },
  { char: "🟨", keywords: ["yellow", "square", "block", "shape"] },
  { char: "🟩", keywords: ["green", "square", "block", "shape"] },
  { char: "🟦", keywords: ["blue", "square", "block", "shape"] },
  { char: "🟪", keywords: ["purple", "square", "block", "shape"] },
  { char: "🟫", keywords: ["brown", "square", "block", "shape"] },
  { char: "⬛", keywords: ["black", "large", "square", "shape"] },
  { char: "⬜", keywords: ["white", "large", "square", "shape"] },
  { char: "◼️", keywords: ["black", "medium", "square", "shape"] },
  { char: "◻️", keywords: ["white", "medium", "square", "shape"] },
  { char: "◾", keywords: ["black", "medium-small", "square", "shape"] },
  { char: "◽", keywords: ["white", "medium-small", "square", "shape"] },
  { char: "▪️", keywords: ["black", "small", "square", "shape"] },
  { char: "▫️", keywords: ["white", "small", "square", "shape"] },
  { char: "🔶", keywords: ["large", "orange", "diamond", "shape"] },
  { char: "🔷", keywords: ["large", "blue", "diamond", "shape"] },
  { char: "🔸", keywords: ["small", "orange", "diamond", "shape"] },
  { char: "🔹", keywords: ["small", "blue", "diamond", "shape"] },
  { char: "🔺", keywords: ["red", "triangle", "pointed", "up"] },
  { char: "🔻", keywords: ["red", "triangle", "pointed", "down"] },
  { char: "💠", keywords: ["diamond", "shape", "dot", "kawaii"] },
  { char: "🔘", keywords: ["radio", "button", "circle", "select"] },
  { char: "🔳", keywords: ["white", "square", "button", "shape"] },
  { char: "🔲", keywords: ["black", "square", "button", "shape"] },
  { char: "🏁", keywords: ["chequered", "flag", "racing", "finish"] },
  { char: "🚩", keywords: ["triangular", "flag", "post", "mark"] },
  { char: "🎌", keywords: ["crossed", "flags", "japanese", "celebration"] },
  { char: "🏴", keywords: ["black", "flag", "pirate", "waving"] },
  { char: "🏳️", keywords: ["white", "flag", "surrender", "peace"] },
  { char: "🏳️‍🌈", keywords: ["rainbow", "flag", "pride", "lgbtq"] },
  { char: "🏳️‍⚧️", keywords: ["transgender", "flag", "trans", "pride"] },
  { char: "🏴‍☠️", keywords: ["pirate", "flag", "jolly", "roger"] },

  // Country Flags (selection of major ones)
  { char: "🇦🇨", keywords: ["ascension", "island", "flag", "country"] },
  { char: "🇦🇩", keywords: ["andorra", "flag", "country", "europe"] },
  { char: "🇦🇪", keywords: ["united", "arab", "emirates", "uae"] },
  { char: "🇦🇫", keywords: ["afghanistan", "flag", "country", "asia"] },
  { char: "🇦🇬", keywords: ["antigua", "barbuda", "flag", "country"] },
  { char: "🇦🇮", keywords: ["anguilla", "flag", "country", "caribbean"] },
  { char: "🇦🇱", keywords: ["albania", "flag", "country", "europe"] },
  { char: "🇦🇲", keywords: ["armenia", "flag", "country", "asia"] },
  { char: "🇦🇴", keywords: ["angola", "flag", "country", "africa"] },
  { char: "🇦🇶", keywords: ["antarctica", "flag", "continent", "south"] },
  { char: "🇦🇷", keywords: ["argentina", "flag", "country", "south america"] },
  { char: "🇦🇸", keywords: ["american", "samoa", "flag", "territory"] },
  { char: "🇦🇹", keywords: ["austria", "flag", "country", "europe"] },
  { char: "🇦🇺", keywords: ["australia", "flag", "country", "oceania"] },
  { char: "🇦🇼", keywords: ["aruba", "flag", "country", "caribbean"] },
  { char: "🇦🇽", keywords: ["aland", "islands", "flag", "finland"] },
  { char: "🇦🇿", keywords: ["azerbaijan", "flag", "country", "asia"] },
  { char: "🇧🇦", keywords: ["bosnia", "herzegovina", "flag", "europe"] },
  { char: "🇧🇧", keywords: ["barbados", "flag", "country", "caribbean"] },
  { char: "🇧🇩", keywords: ["bangladesh", "flag", "country", "asia"] },
  { char: "🇧🇪", keywords: ["belgium", "flag", "country", "europe"] },
  { char: "🇧🇫", keywords: ["burkina", "faso", "flag", "africa"] },
  { char: "🇧🇬", keywords: ["bulgaria", "flag", "country", "europe"] },
  { char: "🇧🇭", keywords: ["bahrain", "flag", "country", "middle east"] },
  { char: "🇧🇮", keywords: ["burundi", "flag", "country", "africa"] },
  { char: "🇧🇯", keywords: ["benin", "flag", "country", "africa"] },
  { char: "🇧🇱", keywords: ["st", "barthelemy", "flag", "caribbean"] },
  { char: "🇧🇲", keywords: ["bermuda", "flag", "territory", "caribbean"] },
  { char: "🇧🇳", keywords: ["brunei", "flag", "country", "asia"] },
  { char: "🇧🇴", keywords: ["bolivia", "flag", "country", "south america"] },
  { char: "🇧🇶", keywords: ["caribbean", "netherlands", "flag", "bonaire"] },
  { char: "🇧🇷", keywords: ["brazil", "flag", "country", "south america"] },
  { char: "🇧🇸", keywords: ["bahamas", "flag", "country", "caribbean"] },
  { char: "🇧🇹", keywords: ["bhutan", "flag", "country", "asia"] },
  { char: "🇧🇻", keywords: ["bouvet", "island", "flag", "norway"] },
  { char: "🇧🇼", keywords: ["botswana", "flag", "country", "africa"] },
  { char: "🇧🇾", keywords: ["belarus", "flag", "country", "europe"] },
  { char: "🇧🇿", keywords: ["belize", "flag", "country", "central america"] },
  { char: "🇨🇦", keywords: ["canada", "flag", "country", "north america"] },
  { char: "🇨🇨", keywords: ["cocos", "islands", "flag", "territory"] },
  { char: "🇨🇩", keywords: ["congo", "kinshasa", "flag", "africa"] },
  { char: "🇨🇫", keywords: ["central", "african", "republic", "flag"] },
  { char: "🇨🇬", keywords: ["congo", "brazzaville", "flag", "africa"] },
  { char: "🇨🇭", keywords: ["switzerland", "flag", "country", "europe"] },
  { char: "🇨🇮", keywords: ["cote", "divoire", "ivory", "coast"] },
  { char: "🇨🇰", keywords: ["cook", "islands", "flag", "oceania"] },
  { char: "🇨🇱", keywords: ["chile", "flag", "country", "south america"] },
  { char: "🇨🇲", keywords: ["cameroon", "flag", "country", "africa"] },
  { char: "🇨🇳", keywords: ["china", "flag", "country", "asia"] },
  { char: "🇨🇴", keywords: ["colombia", "flag", "country", "south america"] },
  { char: "🇨🇵", keywords: ["clipperton", "island", "flag", "france"] },
  { char: "🇨🇷", keywords: ["costa", "rica", "flag", "central america"] },
  { char: "🇨🇺", keywords: ["cuba", "flag", "country", "caribbean"] },
  { char: "🇨🇻", keywords: ["cape", "verde", "flag", "africa"] },
  { char: "🇨🇼", keywords: ["curacao", "flag", "caribbean", "netherlands"] },
  { char: "🇨🇽", keywords: ["christmas", "island", "flag", "australia"] },
  { char: "🇨🇾", keywords: ["cyprus", "flag", "country", "europe"] },
  { char: "🇨🇿", keywords: ["czechia", "czech", "republic", "flag"] },
  { char: "🇩🇪", keywords: ["germany", "flag", "country", "europe"] },
  { char: "🇩🇬", keywords: ["diego", "garcia", "flag", "territory"] },
  { char: "🇩🇯", keywords: ["djibouti", "flag", "country", "africa"] },
  { char: "🇩🇰", keywords: ["denmark", "flag", "country", "europe"] },
  { char: "🇩🇲", keywords: ["dominica", "flag", "country", "caribbean"] },
  { char: "🇩🇴", keywords: ["dominican", "republic", "flag", "caribbean"] },
  { char: "🇩🇿", keywords: ["algeria", "flag", "country", "africa"] },
  { char: "🇪🇦", keywords: ["ceuta", "melilla", "flag", "spain"] },
  { char: "🇪🇨", keywords: ["ecuador", "flag", "country", "south america"] },
  { char: "🇪🇪", keywords: ["estonia", "flag", "country", "europe"] },
  { char: "🇪🇬", keywords: ["egypt", "flag", "country", "africa"] },
  { char: "🇪🇭", keywords: ["western", "sahara", "flag", "territory"] },
  { char: "🇪🇷", keywords: ["eritrea", "flag", "country", "africa"] },
  { char: "🇪🇸", keywords: ["spain", "flag", "country", "europe"] },
  { char: "🇪🇹", keywords: ["ethiopia", "flag", "country", "africa"] },
  { char: "🇪🇺", keywords: ["european", "union", "flag", "europe"] },
  { char: "🇫🇮", keywords: ["finland", "flag", "country", "europe"] },
  { char: "🇫🇯", keywords: ["fiji", "flag", "country", "oceania"] },
  { char: "🇫🇰", keywords: ["falkland", "islands", "flag", "territory"] },
  { char: "🇫🇲", keywords: ["micronesia", "flag", "country", "oceania"] },
  { char: "🇫🇴", keywords: ["faroe", "islands", "flag", "denmark"] },
  { char: "🇫🇷", keywords: ["france", "flag", "country", "europe"] },
  { char: "🇬🇦", keywords: ["gabon", "flag", "country", "africa"] },
  { char: "🇬🇧", keywords: ["united", "kingdom", "britain", "uk"] },
  { char: "🇬🇩", keywords: ["grenada", "flag", "country", "caribbean"] },
  { char: "🇬🇪", keywords: ["georgia", "flag", "country", "asia"] },
  { char: "🇬🇫", keywords: ["french", "guiana", "flag", "france"] },
  { char: "🇬🇬", keywords: ["guernsey", "flag", "channel", "islands"] },
  { char: "🇬🇭", keywords: ["ghana", "flag", "country", "africa"] },
  { char: "🇬🇮", keywords: ["gibraltar", "flag", "territory", "uk"] },
  { char: "🇬🇱", keywords: ["greenland", "flag", "territory", "denmark"] },
  { char: "🇬🇲", keywords: ["gambia", "flag", "country", "africa"] },
  { char: "🇬🇳", keywords: ["guinea", "flag", "country", "africa"] },
  { char: "🇬🇵", keywords: ["guadeloupe", "flag", "caribbean", "france"] },
  { char: "🇬🇶", keywords: ["equatorial", "guinea", "flag", "africa"] },
  { char: "🇬🇷", keywords: ["greece", "flag", "country", "europe"] },
  { char: "🇬🇸", keywords: ["south", "georgia", "sandwich", "islands"] },
  { char: "🇬🇹", keywords: ["guatemala", "flag", "country", "central america"] },
  { char: "🇬🇺", keywords: ["guam", "flag", "territory", "usa"] },
  { char: "🇬🇼", keywords: ["guinea-bissau", "flag", "country", "africa"] },
  { char: "🇬🇾", keywords: ["guyana", "flag", "country", "south america"] },
  { char: "🇭🇰", keywords: ["hong", "kong", "flag", "china"] },
  { char: "🇭🇲", keywords: ["heard", "mcdonald", "islands", "flag"] },
  { char: "🇭🇳", keywords: ["honduras", "flag", "country", "central america"] },
  { char: "🇭🇷", keywords: ["croatia", "flag", "country", "europe"] },
  { char: "🇭🇹", keywords: ["haiti", "flag", "country", "caribbean"] },
  { char: "🇭🇺", keywords: ["hungary", "flag", "country", "europe"] },
  { char: "🇮🇨", keywords: ["canary", "islands", "flag", "spain"] },
  { char: "🇮🇩", keywords: ["indonesia", "flag", "country", "asia"] },
  { char: "🇮🇪", keywords: ["ireland", "flag", "country", "europe"] },
  { char: "🇮🇱", keywords: ["israel", "flag", "country", "middle east"] },
  { char: "🇮🇲", keywords: ["isle", "man", "flag", "uk"] },
  { char: "🇮🇳", keywords: ["india", "flag", "country", "asia"] },
  { char: "🇮🇴", keywords: ["british", "indian", "ocean", "territory"] },
  { char: "🇮🇶", keywords: ["iraq", "flag", "country", "middle east"] },
  { char: "🇮🇷", keywords: ["iran", "flag", "country", "middle east"] },
  { char: "🇮🇸", keywords: ["iceland", "flag", "country", "europe"] },
  { char: "🇮🇹", keywords: ["italy", "flag", "country", "europe"] },
  { char: "🇯🇪", keywords: ["jersey", "flag", "channel", "islands"] },
  { char: "🇯🇲", keywords: ["jamaica", "flag", "country", "caribbean"] },
  { char: "🇯🇴", keywords: ["jordan", "flag", "country", "middle east"] },
  { char: "🇯🇵", keywords: ["japan", "flag", "country", "asia"] },
  { char: "🇰🇪", keywords: ["kenya", "flag", "country", "africa"] },
  { char: "🇰🇬", keywords: ["kyrgyzstan", "flag", "country", "asia"] },
  { char: "🇰🇭", keywords: ["cambodia", "flag", "country", "asia"] },
  { char: "🇰🇮", keywords: ["kiribati", "flag", "country", "oceania"] },
  { char: "🇰🇲", keywords: ["comoros", "flag", "country", "africa"] },
  { char: "🇰🇳", keywords: ["st", "kitts", "nevis", "caribbean"] },
  { char: "🇰🇵", keywords: ["north", "korea", "flag", "asia"] },
  { char: "🇰🇷", keywords: ["south", "korea", "flag", "asia"] },
  { char: "🇰🇼", keywords: ["kuwait", "flag", "country", "middle east"] },
  { char: "🇰🇾", keywords: ["cayman", "islands", "flag", "caribbean"] },
  { char: "🇰🇿", keywords: ["kazakhstan", "flag", "country", "asia"] },
  { char: "🇱🇦", keywords: ["laos", "flag", "country", "asia"] },
  { char: "🇱🇧", keywords: ["lebanon", "flag", "country", "middle east"] },
  { char: "🇱🇨", keywords: ["st", "lucia", "flag", "caribbean"] },
  { char: "🇱🇮", keywords: ["liechtenstein", "flag", "country", "europe"] },
  { char: "🇱🇰", keywords: ["sri", "lanka", "flag", "asia"] },
  { char: "🇱🇷", keywords: ["liberia", "flag", "country", "africa"] },
  { char: "🇱🇸", keywords: ["lesotho", "flag", "country", "africa"] },
  { char: "🇱🇹", keywords: ["lithuania", "flag", "country", "europe"] },
  { char: "🇱🇺", keywords: ["luxembourg", "flag", "country", "europe"] },
  { char: "🇱🇻", keywords: ["latvia", "flag", "country", "europe"] },
  { char: "🇱🇾", keywords: ["libya", "flag", "country", "africa"] },
  { char: "🇲🇦", keywords: ["morocco", "flag", "country", "africa"] },
  { char: "🇲🇨", keywords: ["monaco", "flag", "country", "europe"] },
  { char: "🇲🇩", keywords: ["moldova", "flag", "country", "europe"] },
  { char: "🇲🇪", keywords: ["montenegro", "flag", "country", "europe"] },
  { char: "🇲🇫", keywords: ["st", "martin", "flag", "caribbean"] },
  { char: "🇲🇬", keywords: ["madagascar", "flag", "country", "africa"] },
  { char: "🇲🇭", keywords: ["marshall", "islands", "flag", "oceania"] },
  { char: "🇲🇰", keywords: ["north", "macedonia", "flag", "europe"] },
  { char: "🇲🇱", keywords: ["mali", "flag", "country", "africa"] },
  { char: "🇲🇲", keywords: ["myanmar", "burma", "flag", "asia"] },
  { char: "🇲🇳", keywords: ["mongolia", "flag", "country", "asia"] },
  { char: "🇲🇴", keywords: ["macao", "macau", "flag", "china"] },
  { char: "🇲🇵", keywords: ["northern", "mariana", "islands", "flag"] },
  { char: "🇲🇶", keywords: ["martinique", "flag", "caribbean", "france"] },
  { char: "🇲🇷", keywords: ["mauritania", "flag", "country", "africa"] },
  { char: "🇲🇸", keywords: ["montserrat", "flag", "caribbean", "uk"] },
  { char: "🇲🇹", keywords: ["malta", "flag", "country", "europe"] },
  { char: "🇲🇺", keywords: ["mauritius", "flag", "country", "africa"] },
  { char: "🇲🇻", keywords: ["maldives", "flag", "country", "asia"] },
  { char: "🇲🇼", keywords: ["malawi", "flag", "country", "africa"] },
  { char: "🇲🇽", keywords: ["mexico", "flag", "country", "north america"] },
  { char: "🇲🇾", keywords: ["malaysia", "flag", "country", "asia"] },
  { char: "🇲🇿", keywords: ["mozambique", "flag", "country", "africa"] },
  { char: "🇳🇦", keywords: ["namibia", "flag", "country", "africa"] },
  { char: "🇳🇨", keywords: ["new", "caledonia", "flag", "oceania"] },
  { char: "🇳🇪", keywords: ["niger", "flag", "country", "africa"] },
  { char: "🇳🇫", keywords: ["norfolk", "island", "flag", "australia"] },
  { char: "🇳🇬", keywords: ["nigeria", "flag", "country", "africa"] },

  { char: "🇳🇮", keywords: ["nicaragua", "flag", "country", "central america"] },
  { char: "🇳🇱", keywords: ["netherlands", "flag", "country", "europe"] },
  { char: "🇳🇴", keywords: ["norway", "flag", "country", "europe"] },
  { char: "🇳🇵", keywords: ["nepal", "flag", "country", "asia"] },
  { char: "🇳🇷", keywords: ["nauru", "flag", "country", "oceania"] },
  { char: "🇳🇺", keywords: ["niue", "flag", "territory", "oceania"] },
  { char: "🇳🇿", keywords: ["new", "zealand", "flag", "oceania"] },
  { char: "🇴🇲", keywords: ["oman", "flag", "country", "middle east"] },
  { char: "🇵🇦", keywords: ["panama", "flag", "country", "central america"] },
  { char: "🇵🇪", keywords: ["peru", "flag", "country", "south america"] },
  { char: "🇵🇫", keywords: ["french", "polynesia", "flag", "oceania"] },
  { char: "🇵🇬", keywords: ["papua", "new", "guinea", "oceania"] },
  { char: "🇵🇭", keywords: ["philippines", "flag", "country", "asia"] },
  { char: "🇵🇰", keywords: ["pakistan", "flag", "country", "asia"] },
  { char: "🇵🇱", keywords: ["poland", "flag", "country", "europe"] },
  { char: "🇵🇲", keywords: ["st", "pierre", "miquelon", "flag"] },
  { char: "🇵🇳", keywords: ["pitcairn", "islands", "flag", "uk"] },
  { char: "🇵🇷", keywords: ["puerto", "rico", "flag", "usa"] },
  { char: "🇵🇸", keywords: ["palestinian", "territories", "flag", "palestine"] },
  { char: "🇵🇹", keywords: ["portugal", "flag", "country", "europe"] },
  { char: "🇵🇼", keywords: ["palau", "flag", "country", "oceania"] },
  { char: "🇵🇾", keywords: ["paraguay", "flag", "country", "south america"] },
  { char: "🇶🇦", keywords: ["qatar", "flag", "country", "middle east"] },
  { char: "🇷🇪", keywords: ["reunion", "flag", "island", "france"] },
  { char: "🇷🇴", keywords: ["romania", "flag", "country", "europe"] },
  { char: "🇷🇸", keywords: ["serbia", "flag", "country", "europe"] },
  { char: "🇷🇺", keywords: ["russia", "flag", "country", "europe"] },
  { char: "🇷🇼", keywords: ["rwanda", "flag", "country", "africa"] },
  { char: "🇸🇦", keywords: ["saudi", "arabia", "flag", "middle east"] },
  { char: "🇸🇧", keywords: ["solomon", "islands", "flag", "oceania"] },
  { char: "🇸🇨", keywords: ["seychelles", "flag", "country", "africa"] },
  { char: "🇸🇩", keywords: ["sudan", "flag", "country", "africa"] },
  { char: "🇸🇪", keywords: ["sweden", "flag", "country", "europe"] },
  { char: "🇸🇬", keywords: ["singapore", "flag", "country", "asia"] },
  { char: "🇸🇭", keywords: ["st", "helena", "flag", "island"] },
  { char: "🇸🇮", keywords: ["slovenia", "flag", "country", "europe"] },
  { char: "🇸🇯", keywords: ["svalbard", "jan", "mayen", "flag"] },
  { char: "🇸🇰", keywords: ["slovakia", "flag", "country", "europe"] },
  { char: "🇸🇱", keywords: ["sierra", "leone", "flag", "africa"] },
  { char: "🇸🇲", keywords: ["san", "marino", "flag", "europe"] },
  { char: "🇸🇳", keywords: ["senegal", "flag", "country", "africa"] },
  { char: "🇸🇴", keywords: ["somalia", "flag", "country", "africa"] },
  { char: "🇸🇷", keywords: ["suriname", "flag", "country", "south america"] },
  { char: "🇸🇸", keywords: ["south", "sudan", "flag", "africa"] },
  { char: "🇸🇹", keywords: ["sao", "tome", "principe", "africa"] },
  { char: "🇸🇻", keywords: ["el", "salvador", "flag", "central america"] },
  { char: "🇸🇽", keywords: ["sint", "maarten", "flag", "caribbean"] },
  { char: "🇸🇾", keywords: ["syria", "flag", "country", "middle east"] },
  { char: "🇸🇿", keywords: ["eswatini", "swaziland", "flag", "africa"] },
  { char: "🇹🇦", keywords: ["tristan", "da", "cunha", "flag"] },
  { char: "🇹🇨", keywords: ["turks", "caicos", "islands", "flag"] },
  { char: "🇹🇩", keywords: ["chad", "flag", "country", "africa"] },
  { char: "🇹🇫", keywords: ["french", "southern", "territories", "flag"] },
  { char: "🇹🇬", keywords: ["togo", "flag", "country", "africa"] },
  { char: "🇹🇭", keywords: ["thailand", "flag", "country", "asia"] },
  { char: "🇹🇯", keywords: ["tajikistan", "flag", "country", "asia"] },
  { char: "🇹🇰", keywords: ["tokelau", "flag", "territory", "oceania"] },
  { char: "🇹🇱", keywords: ["timor-leste", "flag", "country", "asia"] },
  { char: "🇹🇲", keywords: ["turkmenistan", "flag", "country", "asia"] },
  { char: "🇹🇳", keywords: ["tunisia", "flag", "country", "africa"] },
  { char: "🇹🇴", keywords: ["tonga", "flag", "country", "oceania"] },
  { char: "🇹🇷", keywords: ["turkey", "flag", "country", "europe"] },
  { char: "🇹🇹", keywords: ["trinidad", "tobago", "flag", "caribbean"] },
  { char: "🇹🇻", keywords: ["tuvalu", "flag", "country", "oceania"] },
  { char: "🇹🇼", keywords: ["taiwan", "flag", "country", "asia"] },
  { char: "🇹🇿", keywords: ["tanzania", "flag", "country", "africa"] },
  { char: "🇺🇦", keywords: ["ukraine", "flag", "country", "europe"] },
  { char: "🇺🇬", keywords: ["uganda", "flag", "country", "africa"] },
  { char: "🇺🇲", keywords: ["us", "outlying", "islands", "flag"] },
  { char: "🇺🇳", keywords: ["united", "nations", "flag", "un"] },
  { char: "🇺🇸", keywords: ["united", "states", "america", "usa"] },
  { char: "🇺🇾", keywords: ["uruguay", "flag", "country", "south america"] },
  { char: "🇺🇿", keywords: ["uzbekistan", "flag", "country", "asia"] },
  { char: "🇻🇦", keywords: ["vatican", "city", "flag", "europe"] },
  { char: "🇻🇨", keywords: ["st", "vincent", "grenadines", "caribbean"] },
  { char: "🇻🇪", keywords: ["venezuela", "flag", "country", "south america"] },
  { char: "🇻🇬", keywords: ["british", "virgin", "islands", "flag"] },
  { char: "🇻🇮", keywords: ["us", "virgin", "islands", "flag"] },
  { char: "🇻🇳", keywords: ["vietnam", "flag", "country", "asia"] },
  { char: "🇻🇺", keywords: ["vanuatu", "flag", "country", "oceania"] },
  { char: "🇼🇫", keywords: ["wallis", "futuna", "flag", "france"] },
  { char: "🇼🇸", keywords: ["samoa", "flag", "country", "oceania"] },
  { char: "🇽🇰", keywords: ["kosovo", "flag", "country", "europe"] },
  { char: "🇾🇪", keywords: ["yemen", "flag", "country", "middle east"] },
  { char: "🇾🇹", keywords: ["mayotte", "flag", "territory", "france"] },
  { char: "🇿🇦", keywords: ["south", "africa", "flag", "africa"] },
  { char: "🇿🇲", keywords: ["zambia", "flag", "country", "africa"] },
  { char: "🇿🇼", keywords: ["zimbabwe", "flag", "country", "africa"] },
  { char: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", keywords: ["england", "flag", "uk", "britain"] },
  { char: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", keywords: ["scotland", "flag", "uk", "britain"] },
  { char: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", keywords: ["wales", "flag", "uk", "britain"] },
];

export default allEmojis;
